### ISSUE TITLE
Failing to pack; Ongoing issue between two computers

### ISSUE THREAD

**Issue by Servius** [ruarai/CompilePal#101]
**Describe the bug**
Having an issue packing assets into the map. Ive attached my logs. 

> Reading BSP...
> Initializing pak file...
> Something broke:
> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
>    at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
>    at System.IO.BinaryReader.ReadInt32()
>    at CompilePalX.Compilers.BSPPack.AssetUtils.findMdlMaterials(String path, List`1 skins)
>    at CompilePalX.Compilers.BSPPack.PakFile.AddModel(String internalPath, List`1 skins)
>    at CompilePalX.Compilers.BSPPack.PakFile..ctor(BSP bsp, List`1 sourceDirectories)
>    at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context)
> 

**Debug.txt**
[debug.log](https://github.com/ruarai/CompilePal/files/4159078/debug.log)

**Additional context**
https://pastebin.com/R7nfSBwe

**Comment by Exactol** [comment]
Can you upload any custom models used in the map? Which version of compile pal are you running and for which game?

**Comment by Servius** [comment]
Running version .25 and .27 Theres a lot of non-hl2/css models being used but all are used in other maps on Gmod, the game Im trying to compile my maps for.

**Comment by Servius** [comment]
Im happy to share the vmf and the required resources if that helps your investigation.

**Comment by Servius** [comment]
Not trying to annoy, gonna tag you to let you know ive responded 👍 @Exactol

**Comment by Servius** [comment]
@Exactol Gonna assume yes to uploading the models. Will do that now.

**Comment by Servius** [comment]
https://drive.google.com/file/d/1pK5t0Dc7ARStt1vImv-HeCeXu1GdisX2/view?usp=sharing

**Comment by Servius** [comment]
https://drive.google.com/file/d/1wzyTdbFICz_1w8yEiSV9eWuI8wlRQbMs/view?usp=sharing

**Comment by Exactol** [comment]
Can't recreate the crash on my end, can you try the latest prerelease?

**Comment by Servius** [comment]
Sure. One moment.

**Comment by Servius** [comment]
So it was able to complete teh compile and actually pack into it. However, it seems to have selectively chosen to not pack in some materials while some CSS textures/models arent recognized as there. I had someone test it with just the .bsp and css mounted to gmod to test. They were having issues mostly on the ship and a few issues with the CSS props on the planet. 

Here are the screens he sent me: 

- https://steamcommunity.com/sharedfiles/filedetails/?id=1992516674
- https://steamcommunity.com/sharedfiles/filedetails/?id=1992516409
- https://steamcommunity.com/sharedfiles/filedetails/?id=1992516347
- https://steamcommunity.com/sharedfiles/filedetails/?id=1992516165

https://drive.google.com/file/d/1dZS5fapgImzh3YMOG6dnLjQMvR_6G_d-/view?usp=sharing

Here is the packed .bsp I sent him ^

**Comment by Servius** [comment]
https://pastebin.com/m545SrYk

Its gotten better but I have one error in the compile. Im using the pack includefolder option to force it to grab everything that is missing from the ship (i hope) and Ive also excludeded one of the 3 directors I was using to keep it as an additional download as required. 

This the last error afaik:

> Error opening C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\maps\gm_buttes_sandyspace.bsp! (Check for write enable)

**Comment by Servius** [comment]
So I think everything is solid. Thank you for your help, the pre-release fixed the issue.
