### ISSUE TITLE
VTFs in directories containing "materials/" don't pack

### ISSUE THREAD

**Issue by xen-000** [ruarai/CompilePal#102]
If the path to a VTF contains "materials/", it will trim out that part when parsing VMT paths, so it becomes an invalid path. For example, this VTF won't be packed:

Before parsing (not the actual path string, this is just an illustration):
"materials/TopHATTwaffle-materials/brick.vtf"

After parsing:
"materials/TopHATTwaffle-.vtf"

**Comment by Exactol** [comment]
I wasn't able to recreate this, have you tried using the latest pre release?

**Comment by xen-000** [comment]
That was on the latest prerelease. 

I think this is where it happens, specifically at line 334.
https://github.com/ruarai/CompilePal/blob/1ba16a16d37d0d09361f2207a7d8f6363eeed74f/CompilePalX/Compilers/BSPPack/AssetUtils.cs#L329-L338

**Comment by Exactol** [comment]
Can you send me a material where this happens?

**Comment by xen-000** [comment]
Anything in this pack https://gamebanana.com/textures/2568

**Comment by Exactol** [comment]
This is now fixed: https://github.com/ruarai/CompilePal/releases/tag/v027.7
