### ISSUE TITLE
packed bsp copies to the vmf folder but not the game

### ISSUE THREAD

**Issue by Fennecai** [ruarai/CompilePal#103]
**Describe the bug**
when using the packer; the packed bsp files copy to the source vmf file and not the game's map folder. this is an issue because:
1. the game doesnt read it's maps from that folder
2. developers of mods and map-packs using this feature will likely not know this at first; and copy/upload the wrong bsp files into their map pack or the workshop etc. (instead of the correct ones, in the vmf folder)
3. the pack can only be run after the copy option; which again means that the bsp in the game folder is not gonna be the same as the bsp that is in the vmf folder now

**Steps to reproduce**
1.create a vmf in a directory where it'll beeasy to see all the files related to it
2.add some custom stuff to the map
3.compile the map with compile pal and packing
4. delete the custom stuff from the game's files or gameinfo.txt to ensure the game cannot read the original files
5. run the map in-game. observe that custom content is not working.
6. go back to the vmf directory, copy the bsp from there into your game's map folder, then run the map again in-game
7. the content works now

**Expected behavior**
I expected the packed bsp to be copied to the game's map folder

**Debug.txt**
there is no debug.txt..... there is, however, a debug.log. its super long though so please let me know if thats what you mean for me to attach here.

**Crash logs**
n/a

**Additional context**
compiling for portal 2; and I'm doing this with maps that use content from different weird folders in different places, which I am able to map with due to clever gameinfo.txt edits.

if it helps to know; i discovered this due to trying to send a mod build to playtesters which only used the maps in the game's actual maps folder- as a result, all the custom content was missing, because i hadnt noticed that the correct maps were in the vmf folder.

im on version 27.5

**Comment by Exactol** [comment]
Can you send the debug.log file?

**Comment by Fennecai** [comment]
[debug.log](https://github.com/ruarai/CompilePal/files/4210586/debug.log)

**Comment by Exactol** [comment]
It looks like bspzip crashed, can you try verifying your game files?

From,
Zach Matuson

**Comment by Fennecai** [comment]
oops. dont know how the bspzip got corrupt in the first place; but that worked. thanks.
