### ISSUE TITLE
files.txt overwritten for every map

### ISSUE THREAD

**Issue by Fennecai** [ruarai/CompilePal#105]
**Describe the bug**
files.txt produced by running with "pack" and dry run enabled, gets overwritten for every map when multiple maps are compiled at one time.

**Steps to reproduce**
1. add multiple vmfs with different custom content in each one
2. run pack with dry-run enabled
3. observe that files.txt will only include the files of one of the maps, not all of them

**Expected behavior**
I expected the files.txt to contain the paths of all custom content from all the maps, but instead it only lists files from a single map.

**Debug.log**
not applicable

**Crash logs**
not applicable

**Additional context**
I am trying to use this with a custom pipeline of sorts, for a portal 2 mod. Essentially i need a way to automatically find and include only the assets the mod actually uses (out of a huge library of stuff it probably doesn't use all of). I created scripts and stuff; which relied upon the assumption that files.txt generated by this program would contain all the custom content. my scripts use the files.txt to copy files to the mod folder.

I realize that compile pal has automated in-bsp packing; but this does not work with the customized compile tools im using, and it is more ideal to include the content as part of the mod and not packed into the bsp maps themselves.

**Comment by Exactol** [comment]
I don’t think combining them all into one file would be the best way, as most people will probably only want the files for each map. Would having a separate files.txt for each map work for you?

**Comment by Fennecai** [comment]
Yeah; that would work. i would probably end up just combining them with my own scripts anyways, but it is still a good solution for my use case. this would need to generate them automatically for each map, however; instead of the current way.

**Comment by Exactol** [comment]
https://github.com/ruarai/CompilePal/releases/tag/v027.8 This should fix your issue. When dry run is enabled, the files.txt that is generated will be named MAPNAME_files.txt stored in the BSPZipFiles folder.
