### ISSUE TITLE
NAV generator doesn't work (csgo)

### ISSUE THREAD

**Issue by granis48** [ruarai/CompilePal#107]
**NAV generator doesn't work**
(in csgo, quickly tested in css too) I wanted to try out the .nav-generator so I wouldn't have to open the map->generate nav->pack after compiling the map. 
However when i hit compile and NAV is checked it will open csgo in a window and load into the compiled map then go to team selection, if there is no nav file for the map it will generate when I join a team like it normally does when launching a map and if there already is one I just join a team and start playing the map. So far the NAV option has just simply launched the map ingame like the GAME option usually does, so the next step would be to exit the game but when I do compilepal crashes with no crashlog or compilelog. 

**Expected behavior**
I expected the NAV option to be similar to the CUBEMAP option where it opens the map ingame, generates the cubemaps and exits it just as it's finished. 

**Debug.log**
The error pops up after exiting the game. When in game it just stops at Generating...
> CompilePal - Nav Generator
Deleting existing nav file.
Generating...
An exception was caught by the ExceptionHandler:
System.IO.IOException: Processen kan inte komma åt filen Z:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\test_nav.log eftersom den används i en annan process.
   vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   vid System.IO.File.InternalDelete(String path, Boolean checkHost)
   vid System.IO.File.Delete(String path)
   vid CompilePalX.Compilers.NavProcess.CleanUp() i C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\NavProcess.cs:rad 144
   vid CompilePalX.Compilers.NavProcess.Process_Exited(Object sender, EventArgs e) i C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\NavProcess.cs:rad 154
   vid System.Diagnostics.Process.OnExited()
   vid System.Diagnostics.Process.RaiseOnExited()
   vid System.Diagnostics.Process.CompletionCallback(Object context, Boolean wasSignaled)
   vid System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object state, Boolean timedOut)
   vid System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object state)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

There's some swedish in there so the translations would be: 
>"The process couldn't access the file [path] because it's already used by another process"
vid = at
rad = row

**Comment by Exactol** [comment]
Which version of Compile Pal is this?

**Comment by granis48** [comment]
I was previously on V027.0 but downloaded the latest release V027.8 too see if it worked there

**Comment by Exactol** [comment]
[Compile Pal 027.9.zip](https://github.com/ruarai/CompilePal/files/4399201/Compile.Pal.027.9.zip)
Can you try this?

**Comment by granis48** [comment]
I tried it out and it's pretty much the same thing. It launches csgo with the map on and goes to team select, after joining a team it builds the nav file and reloads the map as usual, and just like before i then got into the game with nothing special happening. 

I did notice that it deletes the nav file if it exists already but thats about it...

heres the log [debug.log](https://github.com/ruarai/CompilePal/files/4399325/debug.log)

**Comment by Exactol** [comment]
[Compile Pal 027.9.zip](https://github.com/ruarai/CompilePal/files/4399847/Compile.Pal.027.9.zip)
Can you try this version?

**Comment by granis48** [comment]
sry for taking a while to respond. 
I tried two compiles with this version, the first one doing a full compile with NAV at the end of it and the another one with just NAV and nothing else. Unfortunately neither of them made any significant improvements and crashed compilepal like before after exiting the game, although this time it crashed like 2 sec later than usual. 
[debug_1.log](https://github.com/ruarai/CompilePal/files/4408131/debug_1.log)
[debug_2.log](https://github.com/ruarai/CompilePal/files/4408133/debug_2.log)

**Comment by Exactol** [comment]
Can you send me the contents of Z:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\test_nav.log

**Comment by granis48** [comment]
It's empty... I tried compiling normally and whatever to see if anything ever wrote in there but it just stays empty

**Comment by Exactol** [comment]
[Compile Pal 027.9.zip](https://github.com/ruarai/CompilePal/files/4409807/Compile.Pal.027.9.zip)
try this?

**Comment by granis48** [comment]
same thing as before... 
I noticed there were a couple parameters in there so i tried them out just in case something different would happen but none of them seem to help out, "Text Mode" didnt do anything at all and "Hidden" made me unable to open the game. Both generated the nav file like normally but neither closes the game after they're done, so nothing really different. 

test_nav.log is still empty (tried deleting it but it appeared empty again)
error still occurring when exiting the game, staying in the game still does nothing.
[debug.log](https://github.com/ruarai/CompilePal/files/4410024/debug.log)

**Comment by Exactol** [comment]
Can you try running compile pal as Admin and compiling?

**Comment by granis48** [comment]
I tried both the latest release and the last one you sent here, neither did anything noticeably different :(
log from full compile with nav while compilepal is run by admin: 
(again it does nothing until i exit the game where it then crashes and gives the errors)
[debug.log](https://github.com/ruarai/CompilePal/files/4416117/debug.log)

**Comment by Dovahkiin-Warrior** [comment]
Can confirm with Team Fortress 2, game hangs on "Connecting to Server" seemingly endlessly

**Comment by Exactol** [comment]
After doing some investigating, it looks like a recent CSGO update changed the way map CFG files work, which is how Compile Pal automated nav generation. This might take a while to fix.

**Comment by Dovahkiin-Warrior** [comment]
> Can confirm with Team Fortress 2, game hangs on "Connecting to Server" seemingly endlessly

I'd like to update myself on this. The engine's `quit` command appears to be missing from any generated config in your 27.9 release, this appears to be resulting in the game endlessly attempting to nav generate. This however may not apply to CSGO, but I may test that in the near future.

**Comment by granis48** [comment]
damn, wont be expecting a fix any time soon then i guess... 
glad i could bring it to your attention and wish you guys the best of luck :)

**Comment by Dovahkiin-Warrior** [comment]
> damn, wont be expecting a fix any time soon then i guess...
> glad i could bring it to your attention and wish you guys the best of luck :)

Yeah for now I'd just do nav manually then have compilepal do your cubemaps pack and repacks afterwards. Cheers 🙂

**Comment by Exactol** [comment]
Closing this since Counter Strike is now on Source 2. If you think this is still needed feel free to reopen the issue
