### ISSUE TITLE
Add the ability to input your own compile parameters

### ISSUE THREAD

**Issue by Sevin7** [ruarai/CompilePal#11]
Hi ruarai and company,

I've been loving CompilePal and have been using it to compile maps for every game from TF2 to Insurgency and its been a real trooper. However, there is one major situation in which I will still use Hammer's compiler: when I have the game I'm compiling for open and I've been making edits that I want to update quickly into the game. This is pretty much 90% of the time I'm compiling, so the "-hijack" parameter has been extremely useful to me. It recycles the current instance of the game and reloads the map so you don't have to keep closing and opening the game to see changes made to the map. 

I'm sure there are some other, more obscure compile parameters that some people use so it would be nice to be able to manually input your own parameters instead of selecting from a pre-defined list.

Thanks and great job so far!
Sevin

**Comment by ruarai** [comment]
Whilst there's no explicit in-program way to do this, you can add/edit parameters through the .csv files in the Parameters folder.

There's a help file relating to this:
https://github.com/ruarai/CompilePal/blob/master/CompilePalX/Parameters/.help.txt

I've considered adding a way of doing this in-program, but currently it's out of scope.

**Comment by Sevin7** [comment]
Thanks for that, ruarai. I'll check it out.
