### ISSUE TITLE
2x: Caution: Can't load skybox file skybox/militia_hdr to build the default cubemap!

### ISSUE THREAD

**Issue by RalphORama** [ruarai/CompilePal#110]
## Describe the bug
I'm trying to compile a map for Garry's Mod.  I've added `cstrike.fgd` in Hammer so I can use CS:S assets in my map.  In map properties, I set my skybox to `militia_hdr`.  The map compiles fine through Hammer, but when I compile with CP, I get the following warning:

 ```
'Fast' compile finished in 00:00:00
3 errors/warnings logged:
  3 errors/warnings logged for ttt_hillside:
    ● 2x: Caution: Can't load skybox file skybox/militia_hdr to build the default cubemap!
    ● 1x: Info: fastvis = true
```

## Steps to reproduce

1. Open Hammer, from `steamapps\common\GarrysMod\bin`
2. Open Hammer settings and add `cstrike.fgd` from CS:S install folder
3. Create a basic map
4. In Map > Map Properties, change skybox to `militia_hdr` (or any other skybox)
5. Compile the map

## Expected behavior

CP would find the proper skybox and not issue a warning.

## Debug.log

[debug.log](https://github.com/ruarai/CompilePal/files/4506927/debug.log)

## Crash logs

N/a

## Additional context

Log from compiling just with hammer: https://pastebin.com/wPe5huE3

Screenshots:

![image](https://user-images.githubusercontent.com/6566104/79811170-0baa9e80-8343-11ea-8810-3bb443e617db.png)
![image](https://user-images.githubusercontent.com/6566104/79811177-1107e900-8343-11ea-8df6-d1ae1d889558.png)

**Comment by kilroy98** [comment]
Lol, check your **"Log from compiling just with hammer:"** Line 23-24 same error as in the log from CompilePal. It's not a CompilePal problem.

**Comment by Exactol** [comment]
Compile Pal is only a wrapper around the compilers that come with the game, this is an error with the material (this error can usually be ignored).
