### ISSUE TITLE
Error When Packing

### ISSUE THREAD

**Issue by CaskoChan** [ruarai/CompilePal#113]
**Describe the bug**
The map compiles fine but when i try to compile it with the packing option enabled, i get an error.
![CompilePalX_jheRaUaTYO](https://user-images.githubusercontent.com/13442036/82131051-2edc3880-979f-11ea-8aae-e96a1a5bd62c.png)

[debug.log](https://github.com/ruarai/CompilePal/files/4639298/debug.log)

**Comment by Exactol** [comment]
Can you try the latest prerelease?

**Comment by CaskoChan** [comment]
Absolutely will give it a try but, I'm clueless when it comes to compiling source code. Could you please provide a version, thanks.

**Comment by Exactol** [comment]
The download for the pre releases is under the main download. Heres a link https://github.com/ruarai/CompilePal/releases/tag/v027.9

**Comment by CaskoChan** [comment]
Strange, im still getting that error message

**Comment by Exactol** [comment]
Can you upload a clean bsp of the map you are trying to pack?

**Comment by CaskoChan** [comment]
[gm_sundust_b1.zip](https://github.com/ruarai/CompilePal/files/4664410/gm_sundust_b1.zip)

**Comment by CaskoChan** [comment]
Any update?

**Comment by Exactol** [comment]
[Compile Pal 027.10.zip](https://github.com/ruarai/CompilePal/files/4672238/Compile.Pal.027.10.zip)
Can you try this version?

**Comment by CaskoChan** [comment]
Just tested that version with a dryrun and it completed perfectly fine.

![image](https://user-images.githubusercontent.com/13442036/82758242-58a2ea00-9db3-11ea-8a7f-13809711de00.png)

**Comment by CaskoChan** [comment]
Just an update, i tried using the generate particle manifest option but it gave me this error

![image](https://user-images.githubusercontent.com/13442036/82759161-9145c200-9db9-11ea-8fd1-733b9cf7e65a.png)
