### ISSUE TITLE
Generate Particle Manifest Option

### ISSUE THREAD

**Issue by CaskoChan** [ruarai/CompilePal#114]
I tried using the generate particle manifest option but it gave me this error

![image](https://user-images.githubusercontent.com/13442036/82759161-9145c200-9db9-11ea-8fd1-733b9cf7e65a.png)

[2020-05-24T12-26-37.txt](https://github.com/ruarai/CompilePal/files/4673922/2020-05-24T12-26-37.txt)

**Comment by Exactol** [comment]
[Compile Pal 027.10.zip](https://github.com/ruarai/CompilePal/files/4673949/Compile.Pal.027.10.zip)
Try this

**Comment by CaskoChan** [comment]
Thats the version im getting that error on

**Comment by Exactol** [comment]
This is a new build, i just haven't updated the version number yet.

**Comment by CaskoChan** [comment]
![image](https://user-images.githubusercontent.com/13442036/82761324-c78a3e00-9dc7-11ea-83ba-3f1eca758871.png)

perfect, its working! ty
