### ISSUE TITLE
Ability To Add Directory's To Be Searched

### ISSUE THREAD

**Issue by Caskoo** [ruarai/CompilePal#115]
The ability for users to select directory that will be scanned by compile pal. Right now the only option available is Include Directory but that forces anything found to be packed, even if its not used in the map.

**Comment by Exactol** [comment]
Compile Pal will look for content in all search paths in the gameinfo.txt, so if you add your directory there Compile Pal will scan it.

**Comment by CaskoChan** [comment]
Yes thats an option, but that would make hammer load lose files which would make hammer load longer and mounting content a second time.

**Comment by CaskoChan** [comment]
You understand what im saying right?

**Comment by Exactol** [comment]
Yes, but it might take a while to add it. I don't have a lot of free time anymore and am focusing more on bug fixes rather than new features.

**Comment by Exactol** [comment]
Added in #208
