### ISSUE TITLE
[Feature Request] Allow Pack to use a custom file list

### ISSUE THREAD

**Issue by tophattwaffle** [ruarai/CompilePal#118]
**Is your feature request related to a problem? Please describe.**
As a work around to #117 I have opted to use a custom file list on bspzip. 

**Describe the solution you'd like**
Add a "AddList" option as a parameter to the PACK command.

**Describe alternatives you've considered**
For now I've been using a custom command calling the bspzip.exe with manual parameter setup.

**Comment by Exactol** [comment]
Here's a build with the ability to use your own file list. To use it, add the Use File List parameter to the pack step. This will disable the automatic packing detection and use your file list instead.
[Compile Pal 027.12.zip](https://github.com/ruarai/CompilePal/files/4909197/Compile.Pal.027.12.zip)

**Comment by tophattwaffle** [comment]
Hey! The file list feature works.

But is it possible to still have the auto pack work as well? My intention is to use the scanning, along with a manual file list for files that cannot be automatically detected.

**Comment by Exactol** [comment]
[Compile Pal 027.12.zip](https://github.com/ruarai/CompilePal/files/5228795/Compile.Pal.027.12.zip)
Sorry about the long wait, this version includes a new parameter, Include File List, which includes all files from the file list while also performing automated packing, and can be used more than once.
