### ISSUE TITLE
[Bug] CompilePal doesn't pack materials in the root material folder

### ISSUE THREAD

**Issue by bottiger1** [ruarai/CompilePal#119]
**Describe the bug**
CompilePal doesn't pack materials in the root material folder

**Steps to reproduce**
I am trying to recompile this map.  https://gamebanana.com/maps/166253

It has a material at materials/zif1.vmt and materials/zif1.vtf. It does not get packed when I choose the pack option.

The material is present in my folder here, everything else gets packed except for zif1 and zif2, the 2 mats in the base materials folder.

D:\Steam\SteamApps\common\Team Fortress 2\tf\custom\ze_infected_tramway_v1_1_sk\materials

**Expected behavior**
CompilePal should automatically pack files in the root material folder.

Version: 27X TEAM FORTRESS 2

**Comment by Exactol** [comment]
Can you try downloading the latest pre release and see if the bug still happens?

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
