### ISSUE TITLE
Lighting never compiles for Garry's mod

### ISSUE THREAD

**Issue by Fennecai** [ruarai/CompilePal#123]
**Describe the bug**
Maps compiled for Garry's mod always fail to build lighting, and the map is Fullbright in-game.

**Steps to reproduce**
1. Compile a map for Garry's mod with full settings for vrad
2. Play the map in-game
3. Notice its Fullbright.

**Expected behavior**
The map should have the correct lighting. when compiling from hammer, it works fine.

**Debug.log**
[debug.log](https://github.com/ruarai/CompilePal/files/4983153/debug.log)

**Crash logs**
N/A

**Additional context**
Using hammer to compile the map using the same settings for compiler paths, vbsp, vrad, etc. results in a map with correct lighting.  aside from lighting; the map appears to compile correctly.

if it matters; the version I'm using is 27.11x - but this has been occurring for a few versions now.

**Comment by Exactol** [comment]
I'm seeing a lot of invalid model version errors in your log, it might be causing issues

**Comment by Fennecai** [comment]
i found out that certain parameters with vrad dont work with gmod- cant remember atm. which ones though. it has nothing to do with the invalid model errors

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen. The latest version now has compatibility checking for parameters, which should help you avoid this in the future
