### ISSUE TITLE
Ability to move "copy" step to after the "pack" step

### ISSUE THREAD

**Issue by Fennecai** [ruarai/CompilePal#124]
**Is your feature request related to a problem? Please describe.**
I currently have a set-up where I run a custom .bat file in the custom step in order to copy the packed bsp file to the maps folder, after running the pack step. this is kind of hacky since it is basically the same as if the "copy" step came after the "pack" step anyways. the bat file is literally just a single line with the copy command on it.

**Describe the solution you'd like**
I would like the copy step to either be movable by the user so it can be placed after the pack step, or have it just be the final step before "game" by default.

**Describe alternatives you've considered**
Another alternative would be the ability to change the order of any steps the same way you can with custom steps already; via the "order" tab. If your worried about users complaining about broken maps due to fiddling with this un-wisely, you could probably show a small warning message stating that "please be careful when changing the order of compile steps. The end result may be unexpected!"

you could also have an "advanced mode" toggle somewhere that turns this functionality on and off.

**Additional context**
my current work-around:
![image](https://user-images.githubusercontent.com/10889213/88567252-79c2c980-cff4-11ea-9df9-fa40641b2b92.png)

it would be nice to be able to use this same tab to change the order of non-custom steps as well.

**Comment by Exactol** [comment]
The pack step actually copies the packed bsp back to the map folder. The original unpacked bsp becomes name.unpacked. I disabled reordering the default steps because it might cause some confusion if someone accidentally moved one of the steps, but I can look into unlocking them.

**Comment by Exactol** [comment]
[Compile Pal 027.12.zip](https://github.com/ruarai/CompilePal/files/5228833/Compile.Pal.027.12.zip)
Sorry about the wait, I re enabled the ability to re order all compile steps
