### ISSUE TITLE
Failed to pack material from model

### ISSUE THREAD

**Issue by bottiger1** [ruarai/CompilePal#127]
**Describe the bug**
I use a model and everything from it gets packed except for 2 vtf files.

materials\cloud\pupil_l.vtf
materials\cloud\pupil_r.vtf

**Steps to reproduce**
Use this model 
[cloud.zip](https://github.com/ruarai/CompilePal/files/5046214/cloud.zip)
and pack the map.

**Expected behavior**
Everything from the model should be packed.

**Comment by Exactol** [comment]
[Compile Pal 027.12.zip](https://github.com/ruarai/CompilePal/files/5228910/Compile.Pal.027.12.zip)
Fixed in this release
