### ISSUE TITLE
Failed to connect with local client steam process while building cubemaps/nav file

### ISSUE THREAD

**Issue by akshtsaklani7** [ruarai/CompilePal#129]
**Describe the bug**

- Whenever you try to build Cubemaps or Nav File, the program fails to launch the game as soon as it comes to building cubemaps/nav file.

- says that steam needs update. The steam is updated though.

- When you close the error, the compile process completes and the map runs, but without cubemaps/nav file.

- The logs still capture it as "Cubemaps built successfully".

**Steps to reproduce**
Steps to reproduce the behavior.

- Add CSGO map and compile it with Cubemap and/or Nav File options checked.

**Expected behavior**
- The cubemaps and the nav file should get built.

**Debug.log**
Please upload the debug.log file found in your Compile Pal folder.
[debug.log](https://github.com/ruarai/CompilePal/files/5180401/debug.log)

**Crash logs**
If applicable, please upload crash logs found in the CrashLog folder.
NA

**Additional context**

- Happens for both version 27 & version 27.11.

- Tried only with CS:GO.

- Attaching screenshot.

![Capture](https://user-images.githubusercontent.com/55318703/92336643-7412d600-f0c0-11ea-8c72-176ace55e376.JPG)

**Comment by Exactol** [comment]
Is Steam running when you try to build cubemaps?

**Comment by akshtsaklani7** [comment]
Tried it with steam running, steam not running, game already running, game n iij t running. Doesn't work in any of the scenarios.
I get the same result with -game parameter. It fails to launch the game.
The default hammer compiler however never had a problem launching the game.

**Comment by Exactol** [comment]
Can you try using version 26? v27 changed how the game/nav/cubemap commands launched games, this might be a regression.

**Comment by akshtsaklani7** [comment]
Tried 26.2. Same error.

**Comment by Exactol** [comment]
Can you verify the integrity of the game files?

**Comment by maxdup** [comment]
So... this is awkward but as far as I can tell, you can't launch CSGO by its executable anymore. Unless I'm missing an alternative, it must be launched through steam 
```C:\Program Files (x86)\Steam\steam.exe -applaunch 730 -game "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo"```

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
