### ISSUE TITLE
Show elapsed time of a compile alongside completion percentage

### ISSUE THREAD

**Issue by Alydus** [ruarai/CompilePal#130]
**Is your feature request related to a problem? Please describe.**
I find it very difficult to monitor the elapsed time of a compile after returning from a break waiting for it to finish, this feature would allow me to more accurately determine the percentage completion of a compilation on VMFs where I've roughly memorised the total compile time when finished.

**Describe the solution you'd like**
I would like for the total elapsed time to be shown and be updated every second until completion of a compile.

**Describe alternatives you've considered**
I could manually time the compile with a stopwatch however this would require another application and it would be great to see this implemented into CompilePal itself.

**Additional context**
I have created a diagram to demonstrate where I think elapsed time should be shown, however it would also be nice on the titlebar of the application which shows 'PercentageComplete% - Compile Pal 27.9X' currently.

![image](https://user-images.githubusercontent.com/11297569/94189464-abe09280-fea2-11ea-9858-ee732263af81.png)

Thanks for reading.

**Comment by Exactol** [comment]
This is now in the latest pre release https://github.com/ruarai/CompilePal/releases/tag/v027.13
