### ISSUE TITLE
Time Elapsed resets after 24 hours

### ISSUE THREAD

**Issue by PiMoNFeeD** [ruarai/CompilePal#131]
I'm compiling a map for 2 days already on a remote server, and it shows that my elapsed time is only 4 hours even tho Im compiling since yesterday. No errors, crashes, restarts of compiling and etc were at all.

![image](https://user-images.githubusercontent.com/36343425/95118407-eecc2100-0752-11eb-884b-53eafc2b170e.png)

**Comment by Exactol** [comment]
I never expected that anyone would go over 24 hours for a compile, so the hours field only goes up to 24. Should be an easy fix

**Comment by PiMoNFeeD** [comment]
haha, im a hardcore boy https://www.reddit.com/r/hammer/comments/i373pu/what_was_your_longest_map_compile_time/

**Comment by Exactol** [comment]
[Compile Pal 027.14.zip](https://github.com/ruarai/CompilePal/files/5330970/Compile.Pal.027.14.zip)
This should fix the issue

**Comment by PiMoNFeeD** [comment]
cant test right now since im still in the middle of compilation, around 55 hours already :D
