### ISSUE TITLE
"PACK" not working

### ISSUE THREAD

**Issue by Serpensin** [ruarai/CompilePal#134]
**Describe the bug**
In the Output it refers to a directory, which doesn't exist.
(A user called '10zil')

**Steps to reproduce**
- Select a .vmf file created with Hammer. (Just for testing some stuff, cause i'm new to mapping.)
  - This happens everytime if you choose "PACK". Otherwise its fine.
- Publish-Both
- tick "PACK" (leave all other as 'default')
- COMPILE

**Expected behavior**
Packing custom models, sounds, etc. into the .bsp file.

**Debug.log**
[debug.log](https://bit.ly/39gCcTK)

**Crash logs**

**Additional context**
I'm using version 27.13.

**Comment by Exactol** [comment]
Can you translate this line? System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Datei nicht finden

**Comment by Serpensin** [comment]
"The system can't find the specified file."

**Comment by Exactol** [comment]
Can you upload the gameConfigs.json file in the Compile Pal GameConfiguration folder?

**Comment by Serpensin** [comment]
https://bit.ly/3pZwjAl

**Comment by IffyChan** [comment]
same bug, same trouble
log - 
[2020-11-30T16-48-40.txt](https://github.com/ruarai/CompilePal/files/5616292/2020-11-30T16-48-40.txt)

**Comment by Exactol** [comment]
Can you try verifying your game files, and if that doesnt work can you see if X:\\SteamLibrary\\steamapps\\common\\GarrysMod\\bin\\bspzip.exe is a valid path? @IffyChan can you also upload your gameConfigs.json file?

**Comment by Serpensin** [comment]
I don't have bspzip.exe in my folder. For me it is named 'vbsp.exe'.

**Comment by Exactol** [comment]
you need bspzip.exe to pack files. I checked in my GMod bin folder and it was there, can you try verifying your game files?

**Comment by Serpensin** [comment]
I have already redownloaded the whole game.

**Comment by Serpensin** [comment]
I figuered out, why bspzip.exe is not in my folder. I have the x86-64 version installed, where bspzip.exe is missing.

**Comment by Exactol** [comment]
@IffyChan do you also have the x86 version installed?

**Comment by Serpensin** [comment]
For the sake of completeness: If I use the 32-bit version of GMod, the packing works without any problems.

**Comment by IffyChan** [comment]
>  @IffyChan can you also upload your gameConfigs.json file?
sure  [gameConfigs.json](https://pastebin.com/uPMLBV6p)
> @IffyChan do you also have the x86 version installed?
in Betas i use Chromium + 64-bit binaries. so it's x86-64
but i think its still x64 for packing

**Comment by Exactol** [comment]
Does this path exist? `D:\\Program\\Steam\\steamapps\\common\\GarrysMod\\bin\\bspzip.exe`

**Comment by Exactol** [comment]
@IffyChan pinging you because I'm not sure if you are getting notifications for this issue.

**Comment by IffyChan** [comment]
> @IffyChan pinging you because I'm not sure if you are getting notifications for this issue.

aw sorry, have hard time much work bla bla bla...
no, in my bin its dissappear 0_o
but, if i know right, my friend have and he same can't use pack.

**Comment by Exactol** [comment]
Can you try verifying your game files?

**Comment by IffyChan** [comment]
> Can you try verifying your game files?

yes? i reinstall windows in last week and verifying gmod for reg fix

**Comment by Exactol** [comment]
Unfortunately this is out of scope for this project, since this is an issue with Garry's Mod. I suggest asking about why bspzip is missing on a Garry's Mod forum or Discord.
