### ISSUE TITLE
.res file not getting packed

### ISSUE THREAD

**Issue by Pdan4** [ruarai/CompilePal#136]
Used the Include feature in the Pack step, selected `\tf\resource\ui\hudobjectiveflagpanel.res`, 7zip does not show anything from that path in the bsp.

[debug.log](https://github.com/ruarai/CompilePal/files/5611833/debug.log)

**Comment by Exactol** [comment]
What version of Compile Pal are you using? Can you send me the res file?

**Comment by Pdan4** [comment]
Latest (27X, from June 2020). Not sure if it's attaching but the res file is this:

"Resource/UI/HudObjectiveFlagPanel.res"
{				
}

**Comment by Exactol** [comment]
Can you try the latest prerelease?

**Comment by Pdan4** [comment]
Sure, looks like there hasn't been a build release yet.

**Comment by Exactol** [comment]
Sorry about that, created the release but forgot to attach it. Should be updated now

**Comment by Pdan4** [comment]
Error: Failed to resolve internal path for H:\Program Files\Valve\Steam\SteamApps\common\Team Fortress 2\tf\resource\ui\hudobjectiveflagpanel.res, skipping

**Comment by Exactol** [comment]
Can you use the verbose parameter for the pack step and send the full log?

**Comment by Pdan4** [comment]
https://pastebin.com/sap0QVnX

**Comment by Exactol** [comment]
Can you upload the files.txt in the BSPZipFiles folder in Compile Pal after running a compile?

**Comment by Pdan4** [comment]
`materials/PDAN4/MOON/MOON_GLASS_CIRCLE02B.vmt
G:\steamgames\SteamApps\common\Team Fortress 2\tf/materials/PDAN4/MOON/MOON_GLASS_CIRCLE02B.vmt
materials/PDAN4/MOON/MOON_GLASS_CIRCLE02.vmt
G:\steamgames\SteamApps\common\Team Fortress 2\tf/materials/PDAN4/MOON/MOON_GLASS_CIRCLE02.vmt
materials/PDAN4/LIGHTS/GRADIENT_LAMPLIGHT.vmt
G:\steamgames\SteamApps\common\Team Fortress 2\tf/materials/PDAN4/LIGHTS/GRADIENT_LAMPLIGHT.vmt
`
