### ISSUE TITLE
Getting a linux vers working

### ISSUE THREAD

**Issue by karsonatorz** [ruarai/CompilePal#137]
We've got hammer working on linux, it would be fantastic to get this tool working too :D

When game configs are set and running on wine: [pic](https://i.imgur.com/F3qz18T.png)

Is there any way?

**Comment by maxdup** [comment]
The main hurdle when it comes to multiplatform compatibility is WPF support, which we do the UI with. My advice would be:
-Use winetricks to install native .NET.
and/or
-Make sure you use wine 5.7+ which should include WPF support
