### ISSUE TITLE
Program crash if compiler .exe doesn't exist

### ISSUE THREAD

**Issue by PiMoNFeeD** [ruarai/CompilePal#140]
**Describe the bug**
Title says everything

**Steps to reproduce**
Just remove any compiler .exe and try to run a compilation

No crash log is being generated for it
[debug.log](https://github.com/ruarai/CompilePal/files/5921113/debug.log)

![image](https://user-images.githubusercontent.com/36343425/106800832-06200a00-6672-11eb-9ba5-6c39d7315bab.png)

**Comment by Exactol** [comment]
Should be an easy fix, I'll get to it soon

**Comment by Exactol** [comment]
[Compile Pal 027.14.zip](https://github.com/ruarai/CompilePal/files/5938239/Compile.Pal.027.14.zip)
This should fix the issue
