### ISSUE TITLE
Add a warning about missing decal(s)/overlay(s) material(s)

### ISSUE THREAD

**Issue by PiMoNFeeD** [ruarai/CompilePal#141]
**Is your feature request related to a problem? Please describe.**
Compile Pal highlights a lot of warning and errors in the compile log, but for some reason it ignores the most obvious one - about missing decals or overlays materials

**Describe the solution you'd like**
Well, it would be cool to add such highlight cuz' I get confused a lot of times when I compile my maps (I port them from other games) and I see missing textures (and in case of decals - a hella graphical glitch in hammer) despite the log is saying that everything's ok... or not

![image](https://user-images.githubusercontent.com/36343425/107390569-e0c74c00-6b08-11eb-8b1e-7d23aedc7599.png)

**Comment by Exactol** [comment]
Compile Pal uses the interlopers.net/errors compile checker for error highlighting, so unfortunately this is not something that can be fixed on our side.

**Comment by PiMoNFeeD** [comment]
fair enough, thanks
