### ISSUE TITLE
Failed to find executable: xcopy

### ISSUE THREAD

**Issue by PiMoNFeeD** [ruarai/CompilePal#142]
**Describe the bug**
"Copy" macros doesn't work, error is in title

**Steps to reproduce**
Just use "copy"

**Additional context**
Well I updated my compilepal instance to the newest .15 version and it started happening
I have no idea why is this happening this is literally a system32 executable lol
![image](https://user-images.githubusercontent.com/36343425/107638619-e2b41b00-6c80-11eb-9176-94eb98e3e641.png)

**Comment by Exactol** [comment]
Looks like I didn't test the fix for #140 enough, I'll try to fix it by tonight

**Comment by maxdup** [comment]
mhhh, @Exactol technically it would also need to support any executable in the user's PATH. Might be tricky to validate
