### ISSUE TITLE
Its doesnt open unless going into folder its in and opening it with admin

### ISSUE THREAD

**Issue by EmeraldShield99** [ruarai/CompilePal#145]
Doesnt let me open even with shortcut, unless opened in folder as admin.

Just download it and it does this.

**Comment by Exactol** [comment]
Is there a crash log in the Compile Pal folder? Where is Compile Pal located?

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
