### ISSUE TITLE
Cant pack maps in my compiler error message this used to work random issue ocured and has not worked since

### ISSUE THREAD

**Issue by broiiler** [ruarai/CompilePal#147]
My message says this 
![yrZrZBw](https://user-images.githubusercontent.com/47702237/112747156-c90e2f00-8fb3-11eb-8915-2239f6e528f4.png)

No idea how to fix bud id like to use compiler please help

**Comment by broiiler** [comment]
0 27

**Comment by Exactol** [comment]
Can you try the latest prerelease?

**Comment by sunstep** [comment]
Sorry for the necro,  but for anyone who encounters this issue: make sure to do the copy step first before packing. (Just make sure copy is selected at the vbsp, vvis, vrad etc options) then packing should work.

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
