### ISSUE TITLE
env_embers material doesnt pack

### ISSUE THREAD

**Issue by granis48** [ruarai/CompilePal#148]
You can blame valve for this one but I got a map here that uses env_embers which is hardcoded to use the material "particle/fire.vmf" (and by extension particle/fire.vtf). 
It took me some help to find this and to no surprise compilepal doesn't auto pack it so i have to manually specify those files for now, shouldnt be too hard to include those till the next update even though its very niche :)

**Comment by Exactol** [comment]
Should be an easy fix, been busy lately but hopefully I can get around to it soon
