### ISSUE TITLE
Cubemap step launches game at resolution too low to build cubemaps

### ISSUE THREAD

**Issue by RevCosmosis** [ruarai/CompilePal#153]
**Describe the bug**
For some reason, the Cubemaps step is launching the game at a very low resolution, presumably 640x480. When the game tries to buildcubemaps, the resolution is too small and the game crashes.

**Steps to reproduce**
I am reporting this bug on behalf of someone else, so I don't have any details on how this actually happens. The cause is pretty straightforward though. This might as well be a feature request rather than a bug report.

**Expected behavior**
There should probably be additional launch options to let the user control resolution. Alternatively, scan the vmf for cubemap resolution and ensure the game launches at a resolution large enough to ensure the game does not crash. This might also need checking against the screen resolution because I have no idea what happens if you try to launch the game at a resolution bigger than your screen.

**Comment by Exactol** [comment]
This has been resolved through discord. For future reference, the Command Line Argument parameter can be used to pass any command line argument to the game. To set the resolution of the game, you can pass `-w` and `-h` to set the size explicitly
