### ISSUE TITLE
Broken packaging step of the compile process

### ISSUE THREAD

**Issue by Afisz1** [ruarai/CompilePal#155]
Here's the compile code, also i don't have a disc named D:

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: E:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\
Found search path: E:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: E:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: E:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\bin
Found search path: E:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\download
Reading BSP...
Something broke:
System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu. <= (object's refference hasn't been set for the object's presence)
   w (in) CompilePalX.Compilers.BSPPack.BSP..ctor(FileInfo file) w (in) D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\BSP.cs:wiersz 108 <= (line 108)
   w (in) CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context) w D:\a\CompilePal\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:wiersz 230 <= (line 230)
An error cancelled the compile.
Compile forcefully ended.

**Comment by Exactol** [comment]
What version are you using?

**Comment by Afisz1** [comment]
27.16 beta version

**Comment by Exactol** [comment]
Can you send the unpacked bsp file?

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
