### ISSUE TITLE
Trying to compile maps for GE:Source (mod built on HL2)

### ISSUE THREAD

**Issue by AshersD23** [ruarai/CompilePal#157]
Would appreciate any help with this, have tried looking online but unsuccesfully.  I have installed v027 Compile pal and when i try to compile a mp i get this error: "Can't find steam app user info" Screen shot below:

![image](https://user-images.githubusercontent.com/91456636/134869924-3e1e75eb-2a74-4e9c-986f-1b886c18aea6.png)

Game config json in Compile pal looks correct to me:

[
  {
    "GameFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\sourcemods\\gesource",
    "VBSP": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SourceSDK\\bin\\source2007\\bin\\vbsp.exe",
    "VVIS": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SourceSDK\\bin\\source2007\\bin\\vvis.exe",
    "VRAD": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SourceSDK\\bin\\source2007\\bin\\vrad.exe",
    "BSPZip": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SourceSDK\\bin\\source2007\\bin\\bspzip.exe",
    "VBSPInfo": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SourceSDK\\bin\\source2007\\bin\\vbspinfo.exe",
    "VPK": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SourceSDK\\bin\\source2007\\bin\\vpk.exe",
    "GameEXE": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Source SDK Base 2007\\hl2.exe",
    "MapFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\sourcemods\\gesource\\maps",
    "SDKMapFolder": "C:\\Users\\deega\\OneDrive\\Desktop\\Goldeneye\\GE Maps",
    "BinFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\SourceSDK\\bin\\source2007\\bin",
    "Name": "Goldeneye: Source"
  }
]

**Comment by maxdup** [comment]
Is this page of any help? https://developer.valvesoftware.com/wiki/Can%27t_find_steam_app_user_info

**Comment by AshersD23** [comment]
Well , I have tried that but i dont have a Steamappdata.VDF in my config file, tried creating one, tried copying thw whole config folder but no joy.  Usually compile in hammer and VIDE and it works but i want to use compilepal!

**Comment by maxdup** [comment]
Mhhh, can't say I'm familiar with this problem. Does this steam post have any merit? https://steamcommunity.com/app/211/discussions/0/792924412183919525/?l=russian#c4477106086846318279

**Comment by AshersD23** [comment]
Ahhh ok, no problem.  Yeah i have actually managed to track down the original steamappdata.VDF which was apparently removed at some point by Steam. Put it in the varioud config folders in the bin folders butto no avail.  No worries, thank you for the reply.

**Comment by maxdup** [comment]
We might eventually try to replicate and figure out if it's a problem with CompilePal, but I'm not gonna lie to you, development on has slowed down. Make sure to report back if you make any progress.

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
