### ISSUE TITLE
Using the CUSTOM option to use modified build tools. The ARG variables don't work.

### ISSUE THREAD

**Issue by GentlePuppet** [ruarai/CompilePal#160]
The default build options and their arguments work like their should 
IE -game $game$ points to the correct path that it should. 
However, if you try to pass the same args to a custom program it uses the literal string and doesn't resolve it as a variable <path>

Here's a compile log showing what I mean. It starts with a custom version of propper then once that is complete it continues onto vbsp.

```
Starting a 'Test' compile.
Starting compilation of test
Loaded JSON metadata CUSTOM from ./Parameters\CUSTOM\meta.json at order 15

CompilePal - T:\SteamGames3\steamapps\common\Source SDK Base 2013 Multiplayer\bin\propper.exe
Args: T:\SteamGames3\steamapps\common\Source SDK Base 2013 Multiplayer\bin\propper.exe
Args: -game $game$ $vmfFile$
Unable to find gameinfo.txt. Solutions:

1. Read http://www.valve-erc.com/srcsdk/faq.html#NoGameDir
2. Run vconfig to specify which game you're working on.
3. Add -game <path> on the command line where <path> is the directory that gameinfo.txt is in.

Program completed successfully

Valve Software - vbsp.exe (Jul 20 2021)
12 threads
materialPath: T:\SteamGames3\steamapps\common\Team Fortress 2 Hammer++\tf\materials
Loading F:\SteamGames\Valve Maps\Maps - VMFs\test.vmf
Map revision 14
ConVarRef mat_reduceparticles doesn't point to an existing ConVar
fixing up env_cubemap materials on brush sides...
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
Processing areas...done (0)
Building Faces...done (0)
FixTjuncs...
PruneNodes...
WriteBSP...
done (0)
```

I was trying to make a custom compile setup with some modified compiler tools when I found out the variables in the custom args don't work like the default ones.
![image](https://user-images.githubusercontent.com/43224790/148662451-13cfc816-34df-4d92-98bc-9a9ac5311841.png)
![image](https://user-images.githubusercontent.com/43224790/148662466-02366f64-af9e-4866-9cfd-1f8f4a8fa64b.png)

**Comment by Exactol** [comment]
The variables have a slightly different syntax than normal hammer. See here: https://github.com/ruarai/CompilePal/blob/master/Guides/Custom.md

**Comment by GentlePuppet** [comment]
I see. Hmm, after a bit more tweaking and with those variables I've gotten working now. Thanks for the help.

**Comment by worMatty** [comment]
@GentlePuppet Could you tell us how you managed to get this working? I've used the correct arguments (they are actually the same as the ones Hammer uses) but Propper still fails to find gameinfo.txt.

Program Path: `C:\Steam Library\steamapps\common\Team Fortress 2\bin\propper.exe`
Command Line Arguments: `-game $gamedir $path\$file`

Output:
```
Starting a 'Propper' compile.
Starting compilation of propper_models
Loaded JSON metadata CUSTOM from ./Parameters\CUSTOM\meta.json at order 15

CompilePal - C:\Steam Library\steamapps\common\Team Fortress 2\bin\propper.exe
Args: C:\Steam Library\steamapps\common\Team Fortress 2\bin\propper.exe
Args: -game C:\Steam Library\steamapps\common\Team Fortress 2\tf E:\documents\Dropbox\documents\game_dev\level_design\team_fortress_2\work\_ By others\Slav Gael (TF2Maps)\propper_models
Unable to find gameinfo.txt. Solutions:

1. Read http://www.valve-erc.com/srcsdk/faq.html#NoGameDir
2. Run vconfig to specify which game you're working on.
3. Add -game <path> on the command line where <path> is the directory that gameinfo.txt is in.

Unable to find gameinfo.txt. Solutions:

1. Read http://www.valve-erc.com/srcsdk/faq.html#NoGameDir
2. Run vconfig to specify which game you're working on.
3. Add -game <path> on the command line where <path> is the directory that gameinfo.txt is in.

Program completed successfully

'Propper' compile finished in 00:00:00
0 errors/warnings logged:
  No errors/warnings logged for propper_models
```

It seems strange that CPX's compile log should show Propper.exe as an argument for Propper.exe. I thought this might be a bug, and that Propper is receiving an incorrect argument, causing it to not find the gameinfo.txt.

**Comment by Exactol** [comment]
Args is getting printed twice because it does variable substitution on both the program path and command line arguments. The message could be a bit clearer, I'll probably change it in the future. You might need to put quotes around your paths since they contain spaces

**Comment by GentlePuppet** [comment]
Like exactol said try putting quotes in yer args. 
Mine are set up like this ` -game "$gamedir" "$path\$file$ext"`

**Comment by worMatty** [comment]
Thank you both; adding quotes made it work.
