### ISSUE TITLE
Randomly Started Crashing on Startup.

### ISSUE THREAD

**Issue by GentlePuppet** [ruarai/CompilePal#162]
**Describe the bug**
Compilepal crashes on startup for me starting today. 
Quite literally, last night it was working fine, but after waking up and continuing to work on my map compilepal now crashes on startup and I haven't changed anything since. I have no idea what changed and I can't figure out why it's happening.

**Debug.log**
[debug.log](https://github.com/ruarai/CompilePal/files/7917611/debug.log)

**Crash logs**
[2022-01-21T23-19-39.txt](https://github.com/ruarai/CompilePal/files/7917612/2022-01-21T23-19-39.txt)

**Comment by Exactol** [comment]
What game is this for and what version of Compile Pal are you using?

**Comment by GentlePuppet** [comment]
I'm using it with tf2/sdk 2013 and I was using v27 and I tried replacing it with the latest beta 27.16 version and it still crashes on statup.
This is my [gameConfigs.json](https://github.com/ruarai/CompilePal/files/7919502/gameConfigs.json.txt) file. As I already said it was working just fine the day before then it just stopped working. The only thing I changed between sessions was closing compilepal then going to bed. I left my pc on overnight to download some game updates.

If you need anything other information let me know and I'll share.

**Comment by Exactol** [comment]
Can you try deleting you gameConfigs.json and running Compile Pal?

**Comment by GentlePuppet** [comment]
I tried that before and it still crashes. 
These are the logs with a removed gameConfigs.json
[debug log](https://github.com/ruarai/CompilePal/files/7930551/debug.log) 
[crash log](https://github.com/ruarai/CompilePal/files/7930552/2022-01-24T23-09-59.txt)

**Comment by Exactol** [comment]
Sorry for the long delay, something came up and I didn't have time to work on Compile Pal. I created a new build with additional logging, can you try this and send me the debug.txt file?

[Compile Pal 027.19.zip](https://github.com/ruarai/CompilePal/files/8209928/Compile.Pal.027.19.zip)

**Comment by GentlePuppet** [comment]
[Crash_Debug_with_gameconfig.zip](https://github.com/ruarai/CompilePal/files/8216553/Crash_Debug_with_gameconfig.zip)
[Crash_Debug_no_gameconfig.zip](https://github.com/ruarai/CompilePal/files/8216554/Crash_Debug_no_gameconfig.zip)
Here's the debug and crash logs both with and without a gameconfig present.

For what it's worth compilepal 25 does work, but missing the extra include pack options is bleh.

**Comment by Exactol** [comment]
[Compile Pal 027.19.zip](https://github.com/ruarai/CompilePal/files/8886718/Compile.Pal.027.19.zip)
Sorry for the delay again, I've been very busy over the past year, but I should have more free time to work on Compile Pal now. I think I found the issue, please try this new build.

**Comment by GentlePuppet** [comment]
Yes! Whatever you changed has fixed the problem!
Ahh thank you so much.
