### ISSUE TITLE
PACK "Failed to find particle manifest file"

### ISSUE THREAD

**Issue by granis48** [ruarai/CompilePal#165]
I get the error "Failed to find particle manifest file particles\fantasy.pcfFailed to find particle manifest file particles\surf_lt_unicorn.pcfFailed to find particle manifest file particles\thw_river.pcf" when packing this map even though the manifest file exists. 
 
I have most map assets in my google drive so i have that path specified in gameinfo.txt and compilepal prints the directory out during the packing process so it's for sure working. 
 
All three .pcf files are in currentport/particles and the manifest file is in currentport/maps. I'm guessing the check for particle manifest file doesnt look in the wildcard directories or something. 

![image](https://user-images.githubusercontent.com/52294733/151608600-55b3cf62-c573-4ec2-bcb1-f4dfb7d639b9.png)
As you can see it still packs the manifest file correctly, this is because I specified compilepal to include that entire currentport directory because I knew everything in there is used in the map.

**Comment by Exactol** [comment]
Can you try the latest prerelease? A new version was just released that has some fixes for particle manifest packing

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
