### ISSUE TITLE
CompilePal closing after attempting to compile in any preset [GMOD]

### ISSUE THREAD

**Issue by TopOnPC** [ruarai/CompilePal#167]
I'm not sure what's happening but this is what I see after trying to compile
![image](https://user-images.githubusercontent.com/82985914/154819773-33bb3209-830e-4a64-93ef-99c51247eccb.png)

I'm also trying to make a map for GMOD but in the compiler it shows up but without a path
![image](https://user-images.githubusercontent.com/82985914/154819792-176e5fbc-b975-40c2-941e-3800f8430276.png)

**Comment by Exactol** [comment]
Can you send me the gameconfigs.json file in the CompilePal GameConfiguration folder?

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
