### ISSUE TITLE
Improve support for Linux via Wine

### ISSUE THREAD

**Issue by some-username-here1** [ruarai/CompilePal#169]
## Is your feature request related to a problem? Please describe.
In a way, yes; Given how support under wine can be a hit or miss. As how a program works with wine can greatly vary on the complexity of the program and how far wine has gone in terms of supporting those features said program requires.

## Describe the solution you'd like
For CompilePalX to be able to compile a Team Fortress 2 map (or any other source engine game map) with no problems from start to finish.

## Describe alternatives you've considered
1. Using windows all together instead, but it takes time switching between OSes and workflows.
2. Launching with proton instead, given how it has better support in terms of games. One I have not tried yet.
3. Using with mono instead of .NET installed under wine. May be possible, but requires further testing.

## Additional context
N/A

**Comment by maxdup** [comment]
Just letting you know that the CompilePal UI is powered by WPF, which neither mono or proton support. Only wine is worth researching at the current time, maybe there's a chance with the correct .net packages installed. CompilePal is unlikely to switch graphical framework at this point, but maybe a spiritual successor with better technology choices could provide better linux support.
