### ISSUE TITLE
Compile pal crashing without any errors

### ISSUE THREAD

**Issue by sunstep** [ruarai/CompilePal#170]
**Describe the bug**

It's very hard to describe. When I start compile pal it allows me to select a game. Then after selecting a game it just makes a sound and nothing happens. The game selector disappears after selecting a game. A temporary fix is to re-download compile pal and then it works again. But after exiting out of compile pal, there is a chance that the above described bug happens again. Maybe that the crash logs describe the issue better.

**Steps to reproduce**
Steps to reproduce the behavior.

I honestly have no idea how to exactly re-produce it. It happens very randomly. All I know is that it happens after closing compile pal and next time opening it, it could be bugging out like what I described above. 

**Expected behavior**

Compile pal should start after selecting a game, instead it sometimes doesn't

**Debug.log**
Please upload the debug.log file found in your Compile Pal folder.

[debug.log](https://github.com/ruarai/CompilePal/files/8582330/debug.log)

**Crash logs**
If applicable, please upload crash logs found in the CrashLog folder.

[2022-04-28T13-11-45.txt](https://github.com/ruarai/CompilePal/files/8582320/2022-04-28T13-11-45.txt)

**Additional context**

I have no idea whether this is fixable, but I hope this at least makes you aware of potential issues with compile pal.

**Comment by Exactol** [comment]
Hi,
What version of Compile Pal are you using. Please try the latest prerelease if you are not already using it.

**Comment by sunstep** [comment]
I've been using the latest pre-release, that seems the be the version with the issue.

**Comment by Exactol** [comment]
Are you using the Custom build step?

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
