### ISSUE TITLE
I can't pack.

### ISSUE THREAD

**Issue by karl-police** [ruarai/CompilePal#178]
I get this issue ``System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Value cannot be null. (Parameter 'collection'))``

What does it want from me? I use "Publish - Both"

I choose "Include Directory", try to include a scripts directory, but it doesn't pack.

and not even with "Include"

why?

I just want to include this thing that doesn't act as an asset but just a script to test something. Like .zip file drag and drop.

**Comment by Exactol** [comment]
What version of Compile Pal are you using and can you upload the debug.txt file in the Compile Pal folder?

**Comment by Exactol** [comment]
I think I found the issue, can you try this build? https://www.dropbox.com/s/nssmoltkydje3h0/Compile%20Pal%20027.27.zip?dl=0

**Comment by karl-police** [comment]
> I think I found the issue, can you try this build? https://www.dropbox.com/s/nssmoltkydje3h0/Compile%20Pal%20027.27.zip?dl=0

Yeah this fixes the issue and let's me compile it.

Is there an option to save as, as another file?

**Comment by Exactol** [comment]
It's not possible to save the packed map as another file. A copy of the unpacked map gets made named MAPNAME.unpacked if you need it though.
