### ISSUE TITLE
CompilePal doesn't pack r_screenoverlay texture added through AddOutputted Output

### ISSUE THREAD

**Issue by SpookyToad2** [ruarai/CompilePal#181]
CompilePal doesn't detect r_screenoverlay is being used if it's added through AddOutputted Output. Same happens with "play" I believe
![hammerplusplus_CtIqTdftO7](https://user-images.githubusercontent.com/74873411/188313408-27c91952-0a2f-4cde-b3db-49db5f86c5f6.png)

**Comment by Exactol** [comment]
﻿What version are you using? Can you try the latest prerelease?

**Comment by SpookyToad2** [comment]
By latest prerelease you mean experimental version? For some reasons it's not launching for me. Also sorry for such a long time of waiting

**Comment by Exactol** [comment]
Yea, are there any crash logs in the compile pal folder after it fails to launch?

**Comment by SpookyToad2** [comment]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CompilePalX.GameConfigurationParser.Parse(String binFolder) in D:\a\CompilePal\CompilePal\CompilePalX\GameConfiguration\GameConfigurationParser.cs:line 22
   at CompilePalX.GameConfigurationManager.LoadGameConfigurations() in D:\a\CompilePal\CompilePal\CompilePalX\GameConfiguration\GameConfigurationManager.cs:line 150

**Comment by Exactol** [comment]
What game are you compiling for and can you send me the GameConfig.txt from it's bin folder?

**Comment by SpookyToad2** [comment]
Team Fortress 2, 
[GameConfig.txt](https://github.com/ruarai/CompilePal/files/9555564/GameConfig.txt)

**Comment by Exactol** [comment]
Are you using Hammer++? I tried loading your GameConfig and it seemed to have worked fine on v27.30, so it might be a different issue.

**Comment by SpookyToad2** [comment]
Yeah i'm using h++

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
I can confirm that I've seen someone else suffer the exact same issue as Spooky with launching compilepal while being a H++ user. Seems to be a problem with 27.30, 27.29 is fine so maybe the H++ config support added in 27.30 is working incorrectly?

**Comment by Exactol** [comment]
@SpookyToad2  Can you send me the hammerplusplus_gameconfig.txt in the bin/hammerplusplus folder?

**Comment by SpookyToad2** [comment]
Whoops sorry for a long reply.
[hammerplusplus_gameconfig.txt](https://github.com/ruarai/CompilePal/files/9666292/hammerplusplus_gameconfig.txt)

**Comment by Exactol** [comment]
Can you try this build? https://www.dropbox.com/s/hv8cvz4koitrqul/Compile%20Pal%20027.30.zip?dl=0
It should fix the crash on startup, and hopefully the issue packing screen overlays as well

**Comment by SpookyToad2** [comment]
Now CompilePal Launches! I'll check actual packing of r_screenoverlay tomorrow

**Comment by SpookyToad2** [comment]
Nope. Doesn't seem to pack them

**Comment by SpookyToad2** [comment]
Shall I send you test map plus materials? I check github really rarely sadly :(

**Comment by Exactol** [comment]
Yes please

**Comment by SpookyToad2** [comment]
Can I send it to your discord? I don't want to share vmf and materials publically

**Comment by Exactol** [comment]
Yea, my discord is Exactol#2167
