### ISSUE TITLE
CompilePal not opening

### ISSUE THREAD

**Issue by DarvanH548** [ruarai/CompilePal#189]
**Describe the bug**
When i double click the program, it doesnt open

**Debug.log**
Sure, [debug.log](https://github.com/ruarai/CompilePal/files/10323508/debug.log)

**Crash logs**
It doesnt show any crash log

**Comment by Exactol** [comment]
What version of compile pal are you using?

**Comment by DarvanH548** [comment]
i fixed it and idk how
