### ISSUE TITLE
vbsp failure doesn't show full output log

### ISSUE THREAD

**Issue by wyozi** [ruarai/CompilePal#19]
Version 22

Here's what the log shows when I made displacement a func_detail:
```
Starting a 'Fast' compile.
Starting compilation of E:\GModResort\map\resort.vmf
Valve Software - vbsp.exe (Oct 13 2015)
8 threads
materialPath: F:\SteamLibrary\steamapps\common\Counter-Strike Source\cstrike\materials
Loading E:\GModResort\map\resort.vmf
ConVarRef mat_reduceparticles doesn't point to an existing ConVar
EAn error cancelled the compile.
```

Here's the full error line when compiling outside CompilePal: `Error: displacement found on a(n) func_detail entity - not supported (entity 67, brush 0)`

**Comment by ruarai** [comment]
That's weird. It shouldn't stop the line that contains the error from being printed. I'll have a look into it.

**Comment by ruarai** [comment]
Fixed with V023!
