### ISSUE TITLE
Missing StaticPropLightingOld from VRAD

### ISSUE THREAD

**Issue by JonasAlmaas** [ruarai/CompilePal#190]
The parameter StaticPropLightingOld is no longer available.
For now I have just added it back to the json file, but would be nice if it was there.
I know a lot of people including myself use it, so would be nice if it was there.

**Comment by Exactol** [comment]
What version of Compile Pal are you using?

**Comment by JonasAlmaas** [comment]
> What version of Compile Pal are you using?

I just updating to v027. It was there prior to updating.

**Comment by Exactol** [comment]
Can you try the latest prerelease? https://github.com/ruarai/CompilePal/releases/tag/v027.32

**Comment by JonasAlmaas** [comment]
> Can you try the latest prerelease? https://github.com/ruarai/CompilePal/releases/tag/v027.32

I can test it tomorrow. Will get back to you

**Comment by JonasAlmaas** [comment]
> Can you try the latest prerelease? https://github.com/ruarai/CompilePal/releases/tag/v027.32

So, that one does have it. Strange that the version that I was prompted to download through the app didn't

**Comment by Exactol** [comment]
This is a prerelease, so you would only get update notifications if you are already on a prerelease version. The stable versions will only notify you when a new stable release is available
