### ISSUE TITLE
vscript files loaded without .nut are not packed

### ISSUE THREAD

**Issue by rsedxcftvgyhbujnkiqwe** [ruarai/CompilePal#196]
**Compile Pal Version**
V28-RC

**Describe the bug**
If scripts are loaded into an entity just by name instead of with their .nut extension, the pack fails to pick them up.

**Steps to reproduce**
1: Add a script into an entity by name (for example if you have a script named scripts/vscripts/test.nut, just input "test" into the entity)
2: Attempt to pack and get the error

**Expected behavior**
These files should be packed. Despite not having .nut in hammer, TF2 actually does read the files properly, since the extension is not necessary in hammer to have the map read the script files.

**Comment by Exactol** [comment]
This build should fix your issue https://www.dropbox.com/s/6vujs97u5taziey/Compile%20Pal%20027.34.zip?dl=0

**Comment by Thespikedballofdoom** [comment]
This still happens for me, is an output on an entity with RunScriptFile not enough?
