### ISSUE TITLE
TC Round Overviews are not automatically packed

### ISSUE THREAD

**Issue by 14bit** [ruarai/CompilePal#198]
When packing maps for Team Fortress 2, round overview files (such as those used for the map in Territorial Control maps like Hydro, Strata, and National) are not automatically packed.

These files are not referenced by the .vmf at all, but they are always in the same place in the file structure and have the same name as the map they belong to. The three files and their paths are:
```
tf/resource/roundinfo/mapname.res
tf/materials/overviews/mapname.vmt
tf/materials/overviews/mapname.vtf
```
_(these can also be placed in a folder inside the tf/custom folder)_

For example, in my map National the three files I packed in version a6a were:
```
tf/custom/national/resource/roundinfo/tc_national_a6a.res
tf/custom/national/materials/overviews/tc_national_a6a.vmt
tf/custom/national/materials/overviews/tc_national_a2a.vtf
```
Since all these files must be renamed every version, it is common to only change the .res and .vmt file names, and leave the .vtf alone since the .vmt already contains the correct reference to the .vtf inside.

For an example of the file structure, more details on how the round overview works, and a map to test it on, you can use this prefab: https://tf2maps.net/downloads/14bits-improved-territorial-control-prefab.14774/

**Comment by Exactol** [comment]
Can you try this build? https://www.dropbox.com/s/27gwbexhqdbwmeq/Compile%20Pal%20028.1.zip?dl=0
