### ISSUE TITLE
[Bug] Cannot scroll through preset list

### ISSUE THREAD

**Issue by zike1017** [ruarai/CompilePal#201]
**Compile Pal Version**
V028
**Describe the bug**
It is no longer possible to scroll through the preset list. This was a feature in version 27.

**Steps to reproduce**
Create enough presets such that the list extends out of view. Observe as the additional presets are not selectable without increasing the window size.

**Expected behavior**
It should be possible to scroll through the preset list.

**Additional context**
Here is a side by side of versions 27 and 28 showing the lack of scroll bar in the latter.
![image](https://media.discordapp.net/attachments/1084961870731022486/1084965776924086374/image.png)

**Comment by Exactol** [comment]
This build should fix the issue https://www.dropbox.com/s/27gwbexhqdbwmeq/Compile%20Pal%20028.1.zip?dl=0
