### ISSUE TITLE
Pack skybox_swapper skies

### ISSUE THREAD

**Issue by bottiger1** [ruarai/CompilePal#206]
Skies in skybox_swapper https://developer.valvesoftware.com/wiki/Skybox_swapper are not detected and packed.

To fix it you would get the value of key "SkyboxName" and treat it as a skybox material name.

**Comment by bottiger1** [comment]
https://github.com/ruarai/CompilePal/pull/207

**Comment by Exactol** [comment]
Thanks for the pull request, fixed in #207
