### ISSUE TITLE
Add a new parameter to the PACK step to add additional search directories for assets

### ISSUE THREAD

**Issue by statecouncil** [ruarai/CompilePal#208]
**Is your feature request related to a problem? Please describe.**
CompilePal does not read VPKs.

**Describe the solution you'd like**
Add a new parameter to the PACK step to add additional search directories for assets. Not to include the full directory, just to search them for used assets (and then pack those).

**Describe alternatives you've considered**
Alternatively, support reading VPKs in TF2's custom folder

**Additional context**
As discussed on TF2Maps: https://discord.com/channels/217585440457228290/1061647097008496681/1116372414591414292

Cheers!

**Comment by Exactol** [comment]
Pack has a new  `Add Source Directory` parameter, set it to the top level folder where the materials/models/etc folders are located, ex. for tf2 it would be `...Team Fortress 2/tf`

https://www.dropbox.com/s/27gwbexhqdbwmeq/Compile%20Pal%20028.1.zip?dl=0
