### ISSUE TITLE
Game parameter not included when running game

### ISSUE THREAD

**Issue by theatreTECHIE** [ruarai/CompilePal#21]
Version 23
The game parameter "Game; -game;TRUE;Game directory (E.G. tf, cstrike);" wasn't included in the game.csv file, which caused the game not to load properly. Reasonably easy fix for someone who knows how CompilePal works, but not that great for new users.
Also the "sep=;" line wasn't in the game.csv file, and the game parameter in CompilePal didn't show up until I put that in as well.
It would also be nice if the line "Disable Freeze Time; +mp_enableroundwaittime 0;FALSE;Disables the freeze time at the start of rounds.;" was included in the game.csv file, to disable the freeze time at the start of rounds, so that you can start moving immediately. 
Other than that, I love this program, nice work.

**Comment by ruarai** [comment]
-game:
This should already be done by the meta file. It's possible you were having a different issue loading - if you find anything in this regard keep me up to date.

sep=;:
I'm moving the various .csv files to .json files that should be a lot easier to manage in this regard. No more mysterious lines that will probably be deleted by excel anyway.

Disable Freeze Time:
Added in the next version.
