### ISSUE TITLE
Compilepal - Missing components

### ISSUE THREAD

**Issue by AleCTC** [ruarai/CompilePal#214]
**Compile Pal Version**
[Compile Pal V28]

**Describe the bug**
Tried packing some materials from portal2 (using it for CS:GO), and it missed some extra textures used in the .vmt
(In the comments below is a screenshot)

Texture:
effects/fakeportalring_blue

Missed:
models/portals/noise-blur-256x256
models/portals/portal-blue-color
models/portals/portal-mask-dx8
models/portals/portal-blue-color-dx8

Located here: 
common\Counter-Strike Global Offensive\csgo\materials\models\portals

File (fakeportalring_blue.vmt):
https://www.sendspace.com/file/2xunqx (In the comments below is a screenshot)

The .vmt is pretty messy, maybe that could be the reason?
Or the Portalrefract part?

**Steps to reproduce**
Just used the pack process feature. Everything else worked perfectly.

**Expected behavior**
Everything is packaged.

**Debug.log**
None

**Crash logs**
None

**Comment by AleCTC** [comment]
![image](https://github.com/ruarai/CompilePal/assets/17302091/a8058e4a-4822-4fa1-b442-71f21b91eca3)

Screenshot of my "setup"

**Comment by AleCTC** [comment]
![image](https://github.com/ruarai/CompilePal/assets/17302091/2043f883-cfaf-406a-9f85-f28c40c8156c)

In case you don't wanna risk it on the .vmt, here's a screenshot

**Comment by Exactol** [comment]
Can you try this build? https://www.dropbox.com/s/27gwbexhqdbwmeq/Compile%20Pal%20028.1.zip?dl=0

**Comment by Exactol** [comment]
Has your issue been resolved?
