### ISSUE TITLE
Allow manually changing paths/gameinfo for packing

### ISSUE THREAD

**Issue by Fennecai** [ruarai/CompilePal#218]
**Is your feature request related to a problem? Please describe.**
I have been frustrated trying to set this up for a mapbase mod where i have my content in a completely different folder than the mod itself, but im using compile pal as a means to include only what i actually use (since its a folder for all my source engine projects). the problem is that it keep also packing vanilla hl2 assets that dont need to be packed.

**Describe the solution you'd like**
an override parameter of some kind for the pack step that lets me change to either a different ganmeinfo.txt  just for that step, or maybe a different .txt file; with just the custom content paths in it so that vanilla hl2 content isn't packed.

**Describe alternatives you've considered**
i haven't considered alternatives.

**Additional contex**
nothing that i can think of

**Comment by Fennecai** [comment]
oops- sorry, it appears that the issue im experiencing may be part of the teamspen210 tools postcompiler and not this.

**Comment by Exactol** [comment]
I believe this should be possible now. You can use the `Add Source Directory` parameter to add a new search path outside of the mod folder and the `Exclude Directory` option to prevent packing hl2 assets
