### ISSUE TITLE
Adding new parameters doesn't seem to work?

### ISSUE THREAD

**Issue by RevCosmosis** [ruarai/CompilePal#22]
I have my Hammer expert compile options set to back up my .vmf on every compile, so I figured I would try and get CompilePal to do the same. Maxdup pointed me in the direction of creating custom .meta and .csv files in the Parameters folder, but I haven't been able to get anything to work.

My method was to copy the contents of copy.meta/.csv and modify the contents to do what I wanted, and the new compile step appears in the program just fine. However, when the compile process gets to the new step, the entire program stops responding.

Here are the contents of "back.meta":

`BACK
CopyTool.exe
back.csv
 -copyDestination $mapCopyLocation$ -copySource $bsp$
6.0
False
true`

back.csv is identical to copy.csv (I also tried making back.meta file reference copy.csv, but it didn't change anything). This file is pretty much identical to copy.meta (aside from the name, referenced .csv, and position in the queue). I also adjusted game.meta to appear later than BACK in the queue.

I have also tried sticking BACK at the end of the queue to avoid any of the default parameters in the queue from being in spots that the program might not expect.

My conclusion is that something about the compile process isn't completely based on files outside the program, and it doesn't know how to handle files it isn't built to recognize. I'd love to see custom compile parameters work (especially through the UI itself!) for people who do backups/people who need to use [vmfii](https://github.com/Metapyziks/VMFInstanceInserter).

**Comment by maxdup** [comment]
What happened is compilepal crashed because CopyTool.exe doesn't exist anymore and couldn't be launched. The copy.meta file was misleading in this case. Running executables from meta files does work but crashes when the executable doesn't exist.

**Comment by ruarai** [comment]
What @maxdup said sounds about right. CopyTool.exe isn't used anymore, and was removed in the latest update.

You should be able to copy it from the older version if you just want to keep this functionality.

However, the idea of a generic copy functionality for things like backups does sound useful. Will need to consider for future versions.
