### ISSUE TITLE
"searchpaths" line in compilepal is case sensitive and breaks asset packing if not capitalised as SearchPaths

### ISSUE THREAD

**Issue by Radial36** [ruarai/CompilePal#224]
**Compile Pal Version V028.2**

**Describe the bug**
"searchpaths" line in gameinfo is case sensitive when it shouldn't be, breaks asset packing if not capitalised as SearchPaths

**Steps to reproduce**
1. Rename the "SearchPaths" line in gameinfo.txt to "searchpaths"

**Expected behavior**
Asset packing would behave as normal.

**Comment by Exactol** [comment]
This build should fix the issue https://www.dropbox.com/scl/fi/izhbxvjcj6knk27ezl00l/Compile-Pal-028.2.zip?rlkey=iiekwopnn2tpbbwdu98nu0erp&dl=0
