### ISSUE TITLE
CompilePal not running custom compilers in their `bin` folder causes nonexistant leaks and mangles instances

### ISSUE THREAD

**Issue by 14bit** [ruarai/CompilePal#228]
**Compile Pal Version**
v28 + v28.2 + likely all older versions

**Describe the bug**
When compiling, CompilePal does not set the directory that the compilers run in to the `bin` folder they are stored in, like Hammer and Hammer++ do. This can cause leaks where none exist and cause entities in instances to be placed incorrectly in some custom compilers. This can make compiling for SourceMods with custom compilers like TF2C impossible in CompilePal.

**Steps to reproduce**
1. Install and set up TF2C and its custom compile tools as listed here: [TF2C Mapping Setup](https://wiki.tf2classic.com/wiki/Setting_up_Hammer)
2. Create a CompilePal configuration for TF2C and its custom compilers
3. Create a map that contains an instance and/or 3D skybox that would place entities outside of the sealed area if the entities in that instance/3D skybox were translated to be centered on `0 0 0` (I can provide a .vmf privately that does this if needed)
4. Compile in Hammer/Hammer++ to see that it compiles with no leaks
5. Compile in CompilePal to see that it leaks when using the same `.vmf` with no changes

You can test that this nonexistent leak is caused by running the compilers in the wrong place by reproducing this behavior from the command line, too:
1. Follow steps 1-3 above
2. Open command line on desktop, and run `"C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Multiplayer\bin\vbsp_tf2c.exe" -game "C:\Program Files (x86)\Steam\steamapps\sourcemods\tf2classic-beta" "C:\Users\Eric\iCloudDrive\TF2_Mapping\Maps\TF2C\pl_jinn.vmf"` (or the equivalent for your setup and `.vmf`)
3. The map will fail to compile, saying the map is leaking
4. Run `cd "C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Multiplayer\bin"` to move to the `bin` folder the compilers are stored in
5. Run the same command as in Step 2
6. The map will now compile with no leaks

**Expected behavior**
The map compiles without leaking or misplacing entities, like it does when compiling directly from Hammer and Hammer++.

**Debug.log**
[debug.log](https://github.com/ruarai/CompilePal/files/13877170/debug.log)
^ This leak does not exist, there is no entity at that location in the `.vmf` (I can provide the `.vmf` privately if needed for verification)

**Crash logs**
N/A

**Additional context**
Sometimes maps compile fine in CompilePal when using custom compilers set up this way, seemingly those without instances or 3D skyboxes. All maps I've tried with 3D skyboxes and instances have bugged out, all those without work fine. You can read the whole discussion of how we figured this out in the TF2Maps Discord: [Link to Discussion](https://discord.com/channels/217585440457228290/1194111994303873034/1194119583838249070)

**Comment by Exactol** [comment]
Can you try this build? https://www.dropbox.com/scl/fi/izhbxvjcj6knk27ezl00l/Compile-Pal-028.2.zip?rlkey=iiekwopnn2tpbbwdu98nu0erp&dl=0

**Comment by 14bit** [comment]
This build seems to fix the issue!
I tested it with two different maps that caused issues with previous versions of CompilePal, and they compile correctly without leaks and entities that were previously placed incorrectly are now in their proper places.
