### ISSUE TITLE
Issue when compiling/packing

### ISSUE THREAD

**Issue by MayaMogus** [ruarai/CompilePal#230]
**Compile Pal Version**
28.2
**Describe the bug**
I am new to compilepal but whenever i tried to pack my map and had an error everytime. i tried compiling and still had erros

**Steps to reproduce**
i dont know. just happens when i compile or pack. i had the pack parameter set to exclude my custom folder sometimes, but the error persisted without it too

**Expected behavior**
map be packed/compiled

**Debug.log**
[debug.log](https://github.com/ruarai/CompilePal/files/13907410/debug.log)

**Crash logs**
If applicable, please upload crash logs found in the CrashLog folder.
nope

**Additional context**
if this is at all anything of my fault/on my end i apologize and thank u for checking this anyway

**Comment by Exactol** [comment]
Can you try this build and upload the debug.log? I added some more debug printing to find the file causing the issue https://www.dropbox.com/scl/fi/izhbxvjcj6knk27ezl00l/Compile-Pal-028.2.zip?rlkey=iiekwopnn2tpbbwdu98nu0erp&dl=0

**Comment by MayaMogus** [comment]
I figured out the what file was causing the issue myself and deleted the file, sorry. But thanks for looking into it
