### ISSUE TITLE
VMT file with no line breaks is not recognized when packing custom content

### ISSUE THREAD

**Issue by MamiKeRiko** [ruarai/CompilePal#237]
On version 28X (Team Fortress 2)

Attempting to pack a material into your map whose VMT is written in one line or is missing like breaks, which is valid and works in-game,  said material will not be packed correctly into the map, leading to a missing texture.

**Steps**
- Create or download a material with a VMT file as previously described. In my case it was the materials of the following door assets: https://tf2maps.net/threads/industrial-doors.43507/
- Add said material or asset using the material to any map.
- Compile said map with the PACK process enabled.
- In-game, set sv_pure to 2 and load your map.

**Expected behavior**
The material or model should be properly packed into the map, since the VMT is fully functional despite its unorthodox structure and thus displays correctly when the asset is contained in your tf/custom folder and sv_pure isn't 2.

**Debug.log**
[debug.log](https://github.com/ruarai/CompilePal/files/15001219/debug.log)

**Comment by Exactol** [comment]
Can you try this build? https://www.dropbox.com/scl/fi/gmfex44y1l8breffnxnoj/Compile-Pal-028.4.zip?rlkey=9234dk83qbrhe0i4fopgsz5go&st=wmtd87om&dl=0
