### ISSUE TITLE
CompilePalX.exe is being detected as a trojan by Windows Defender

### ISSUE THREAD

**Issue by arctic-dino** [ruarai/CompilePal#238]
![Screenshot 2024-04-20 101615](https://github.com/ruarai/CompilePal/assets/111310777/219957ee-f9da-45a6-aff8-93d4d4854d44)

Just downloaded release 028.3 and got a popup claiming it to be a trojan.

**Comment by Exactol** [comment]
Its safe to ignore, since Compile Pal is not signed (costs money), it sometimes gets falsely marked as malware
