### ISSUE TITLE
Project can't compile

### ISSUE THREAD

**Issue by Rushaway** [ruarai/CompilePal#239]
**Compile Pal Version**
Latest

**Describe the bug**
The github action can't compile the program. 

**Steps to reproduce**
Draft a new release with a new tag

**Expected behavior**
Generate the exe

**Debug.log**
Please upload the debug.log file found in your Compile Pal folder.
N/A

**Crash logs**
If applicable, please upload crash logs found in the CrashLog folder.
N/A

**Additional context**
Issue was introduce in https://github.com/ruarai/CompilePal/commit/d83020b114b59aa039d07d562611cb0f131ceb54 with `new SettingsWindow().Show()`
Build log: https://github.com/Rushaway/CompilePal/actions/runs/8886250259

**Comment by Exactol** [comment]
Sorry, I must have accidentally committed some unfinished code. I just pushed the rest of the commit, try rebuilding now

**Comment by Rushaway** [comment]
Thanks for the commit, unfortunately it keeps not compiling.
Here logs: https://github.com/Rushaway/CompilePal/actions/runs/8918673034/job/24493643477#step:7:179

**Comment by Exactol** [comment]
Did you merge the latest changes into your fork? It worked when I tried building itOn May 2, 2024, at 12:39 AM, Rushaway ***@***.***> wrote:﻿
Thanks for the commit, unfortunately it keeps not compiling.
Here logs: https://github.com/Rushaway/CompilePal/actions/runs/8918673034/job/24493643477#step:7:179

**Comment by Rushaway** [comment]
> Did you merge the latest changes into your fork? It worked when I tried building it

Yes, feel free to check my repo. It's up to date with your.

**Comment by Exactol** [comment]
Looking at your build, it looks like it was run for tag v028.4 (https://github.com/Rushaway/CompilePal/releases/tag/v028.4) which is one commit behind master. The missing commit adds the SettingsWindow related changes, so I think you just need to create a new tag and run another build pipeline
