### ISSUE TITLE
Failed to resolve internal path for C:\[pathfile], skipping

### ISSUE THREAD

**Issue by goog00goog** [ruarai/CompilePal#242]
Compile Pal v028

whenever i try to pack my custom vtf and vmt, even if they're in the same folders, they are never found, or, at least thats what i think.

**Steps to reproduce**
have bsp in "maps" folder and the vtf & vmt in "materials" folder, open compile pal, select hl2, launch, select the bsp, then select the materials folder for the "pack" preset. click compile

**Expected behavior**
i thought it would find the materials in the folder and pack it into the bsp

**Debug.log**
```
Starting a 'Pack' compile.
Starting compilation of aiimageplace

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Multiplayer\hl2\custom\
Found search path: C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Multiplayer\hl2
Found search path: C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Multiplayer\hl2
Found search path: C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Multiplayer\hl2\bin
Reading BSP...
Initializing pak file...
Failed to resolve internal path for C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\ai_map\materials\aidecal.vmt, skipping
Failed to resolve internal path for C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\ai_map\materials\aidecal.vtf, skipping
Writing file list...
Running bspzip...
Finished!
---------------------
0 materials found
0 models found
0 particle files found
0 sounds found
---------------------

'Pack' compile finished in 00:00:02
```
**2 errors/warnings logged:
  2 errors/warnings logged for aiimageplace:
    ● 2x: Error: Failed to resolve internal path for C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\ai_map\materials\aidecal.vmt, skipping**

**Crash logs**
none

**Additional context**
ill leave some files here
[map related files](https://drive.google.com/drive/folders/1f6a132ecXswqM3cFCWUtJVmo6KetkWpv?usp=sharing)

**Comment by Exactol** [comment]
Garry’s mod is not compatible with the pack step, they have their own way to pack maps

**Comment by goog00goog** [comment]
thank you for telling me
