### ISSUE TITLE
Not picking csgo content

### ISSUE THREAD

**Issue by pab14567** [ruarai/CompilePal#27]
So I don't know if I need to re-install compile pal again just for it to pick it up because I transferred from a usb, or is it because it won't. 

On my other pc aswell it wouldn't pick up the sdk content even after I launched it

**Comment by maxdup** [comment]
Switching PC is only an issue if the GameConfiguration\gameConfig.json file ends up pointing to the wrong directories (the file can be deleted if it goes wrong).

Other than that you'll have to be more specific. Did the console output anything?

**Comment by pab14567** [comment]
No, it just doesn't pick it up. now when I re-installed it, it only picks up css and not hl2 or css, even though I've ran source sdk 2009 and also opened up css hammer

**Comment by maxdup** [comment]
okay, well, the way things normally work is compilepal will fetch the gameconfig.txt from the last opened version of hammer. So try opening the csgo sdk and relaunch compilepal to see if csgo is in there.

If that doesn't work, you can patch in any game you want into Compilepal\GameConfiguration\gameConfig.json

**Comment by ruarai** [comment]
@pab14567 Yes, sadly we can't detect games without hammer/source sdk being launched for each game to do the work for us. Not much of a way around it either.

maxdup's advice should work here, and if it doesn't this is definitely a more interesting issue

**Comment by pab14567** [comment]
@ruarai Yeah I tried adding it manually and it wouldn't even start. I got ever file path correct and it wouldn't start at all,

**Comment by ruarai** [comment]
That's definitely weird. 

Can you attach a copy of the gameConfigs.json file? And maybe the debug.log file if it exists? There may also be a crash log in the "CrashLogs" folder although it might not work given where the error is occurring.
