### ISSUE TITLE
Compilepal won't pack custom vmts of stock textures used as decals (infodecal)

### ISSUE THREAD

**Issue by FraganciaGH** [ruarai/CompilePal#30]
Hello. 
As the title says, Compilepal doesn't pack custom vmts for stock textures to be used as decals for the infodecal entity I always have to manually pack my custom vmts in with VIDE, it would be nice if Compilepal could pack those automatically.

Thanks for taking the time reading this report.

**Comment by maxdup** [comment]
I will look into it. Thanks.

**Comment by maxdup** [comment]
Issue fixed, this will be shipped with v25. 1a0e42b231524ee8633a90838f4d4d643aaa5f8a
in the meantime, you can add support for decals yourself by adding "texture" to "Compile Pal 024\Keys\vmfmaterialskeys.txt"
