### ISSUE TITLE
Feature request: Add a custom command option

### ISSUE THREAD

**Issue by magnusjjj** [ruarai/CompilePal#35]
Hi!

I wrote an external dependency resolver, and wanted my friend to test it. He, however, uses compilepal. It doesn't allow custom commands directly. I figured out how to make a command directory, which works, but it seems like a bit of a hassle.
I could potentially create 10 commands that is just 'launch command' with different priorities, but that also seems.. uh. Unintentionally crap.

Which would be the best way to go about it? I could potentially code a fix for it myself, but before that I would like to have some input as to the best way to do it :).

**Comment by maxdup** [comment]
While there is no documentation or ui to support that, compilepal commands are are meant to be fully customizable. The way this is done is via json files in CompilePalX/Parameters/ you'll want to copy the structure in there to add your own command.
The way this works is the meta.json file will accept any exe in it's path parameter. You'll also find many other options. For example, the "order" parameter determines when your command should be ran, relative to other commands.
To distribute your dependency solver as a compilepal plugin, you should consider bundling a meta.json and a parameters.json with your executable for easy installation.

side note, have you had a look at compilepal's dependency solver? (the pack option). It's already very advanced. The codebase is not exactly clean but you're welcome to contribute to it if you're interested.

**Comment by Exactol** [comment]
This has been added with the new custom compile step
