### ISSUE TITLE
Strange Stuttering/Freezing Issue

### ISSUE THREAD

**Issue by Matt2468rv** [ruarai/CompilePal#37]
When I use CompilePal, it has a strange issue that causes my entire computer to freeze/stutter.  It only happens when the CompilePal window is selected, AND if I mouse over any selectable element in the CompilePal window.  The mouse and screen repeatedly freeze to an almost unusable state.  It stabilizes after a few seconds of not mousing over any element in the CompilePal window, but begins again as soon as you mouse over any selectable element.  If the CompilePal window is NOT selected, it does not stutter when mousing over any selectable element in the CompilePal window.

**Comment by ruarai** [comment]
This is very weird. What version of Windows are you running?

**Comment by Matt2468rv** [comment]
OS: Windows 10 Home
CPU: Intel Core i7-7700HQ CPU @ 2.80GHz
GPU: GeForce GTX 1070 (laptop)
RAM: 64GB

**Comment by Matt2468rv** [comment]
Also, it is not consuming a lot of CPU usage when this happens.  So I am not sure what's happening.  But it definitely seems to be a bug with CompilePal.

**Comment by Matt2468rv** [comment]
More detail - during a compile, it causes my computer to stutter/freeze during most parts of the compile process, even without mousing over anything.  This only happens when the CompilePal window is selected.  If it is not selected, the compile process goes on without causing a stutter, even when mousing over anything.

**Comment by ruarai** [comment]
Sounds like there might be an issue with the GPU acceleration if there's no CPU usage spikes.

The stuttering sounds like its occurring whenever a WPF UI update occurs, as this coincides with the mousing over (we don't actually do anything ourselves here, but I feel like WPF could trigger an update anyway) and compilation (logging lines of text).

I'll need to write a quick bit of debug code to check if you're getting GPU acceleration or not when I get home.

**Comment by ruarai** [comment]
[Compile Pal Test Version.zip](https://github.com/ruarai/CompilePal/files/1414210/Compile.Pal.Test.Version.zip)


This is a quick debug build that prints these two lines into the output when you launch.

RenderCapability.Tier:2
RenderCapability.IsShaderEffectSoftwareRenderingSupported:True

If your tier is less than 2, that may be the issue.

If not, I have no idea.

**Comment by Matt2468rv** [comment]
RenderCapability.Tier:2
RenderCapability.IsShaderEffectSoftwareRenderingSupported:True

Any idea what could be wrong?

**Comment by ruarai** [comment]
[Compile Pal Test Version.zip](https://github.com/ruarai/CompilePal/files/1414486/Compile.Pal.Test.Version.zip)

Honestly have no idea. This version has an update version of the UI framework we use. Might help?

**Comment by Matt2468rv** [comment]
That test version also has the issue. :(

**Comment by ruarai** [comment]
Last ditch attempt...

[DebugNET45.zip](https://github.com/ruarai/CompilePal/files/1414549/DebugNET45.zip)

Let me know if this runs poorly. It's the demo app for the UI framework we use. If you don't get issues with this, then we at least know it's on Compile Pal's end.

**Comment by Matt2468rv** [comment]
I'll give it a shot later this afternoon or evening and let you know!

**Comment by Matt2468rv** [comment]
The issue does happen with that demo app for the UI framework.  So it looks like it's the UI and not CompilePal itself.  Very strange this is happening though.  I guess I can't ask you to change the entire UI for my sake, but I'd have to imagine this happens to some others who aren't speaking up about it as well.

**Comment by ruarai** [comment]
Yeah this is a bit disappointing to hear. Whether it's an issue with WPF or MahApps itself it's not going to be an easy issue to fix on our end.

I guess if you're still looking for a fix, it's possible that updating either your .NET framework or all your graphics drivers might help.

Sad to say there isn't much more it looks like we can do here.

**Comment by ruarai** [comment]
It's also possible that if it is an issue with https://github.com/MahApps/MahApps.Metro then it's something they might be interested in. You might have some luck raising the issue there.

**Comment by Matt2468rv** [comment]
I'll see if there's anything I can do on that end.  Either way, thanks for the help narrowing it down.  I can still use CompilePal, but it's just a slow process setting up the compile.
