### ISSUE TITLE
Version Number Incorrect in V25 (says it's V24)

### ISSUE THREAD

**Issue by Matt2468rv** [ruarai/CompilePal#38]
In the latest release (V25) of CompilePal, the version.txt still has 24 in it, causing the message to pop up saying that there is a newer version available.  It's easy to fix since I just changed the number in the text file, but I just wanted to let you know so that it can be fixed.

**Comment by ruarai** [comment]
Well that was a bit silly of me. I've fixed it in the release. Thanks!
