### ISSUE TITLE
It is so broken in portal 2

### ISSUE THREAD

**Issue by asd417** [ruarai/CompilePal#39]
when I try to full compile the map, it does very quick fullbright compile, starts the game, (even though I asked it to not open Game) after compile, and crashes after flashing random screenshots of the map in 1/4 size of the window saying 'map not found in portal2_dlc3'

**Comment by ruarai** [comment]
This might be an issue with Compile Pal, but it sounds like you've just got the 'CUBEMAPS' option enabled - that's what causes the game to launch and take screenshots (I'm not sure if this works with Portal 2).

But CUBEMAPS isn't enabled on the default FULL preset, so you might just need to check that you haven't enabled it by accident.

Let me know if you need any help.

**Comment by asd417** [comment]
Sorry, compilepal not compiling full was simply because I had BEE mod installed which changes the vbsp.
However, I noticed that it does not properly pack custom contents. This could also be caused by other programs however it would be great if you could check if this is the case.

**Comment by Exactol** [comment]
Closing stale issues
