### ISSUE TITLE
Map keeps leaking, even though hammer says theres no leaks

### ISSUE THREAD

**Issue by Ewber** [ruarai/CompilePal#40]
At the end of compiling, it says its leaked, but when I look at the compile log, it doesnt say ** leaked **

**Comment by maxdup** [comment]
seems very weird, can you copy/paste your full log here?

**Comment by Ewber** [comment]
I kinda lost it after doing a different compile, and for some strange reason, its not full bright and leaked anymore.

**Comment by Ewber** [comment]
After the compile thing finished it still has this thing at the end.
`Starting a 'Normal - Pack' compile.
Starting compilation of koth_mudlands_a2
BuildFacelights:     0...1...2...3...4...5.Valve Software - vbsp.exe (Oct 14 2017)
2 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\materials
Loading C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.vmf
ConVarRef mat_reduceparticles doesn't point to an existing ConVar
Patching WVT material: maps/koth_mudlands_a2/cp_mountainlab/nature/groundtograss001_wvt_patch
fixing up env_cubemap materials on brush sides...
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (1)
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
Processing areas...done (0)
Building Faces...done (0)
Chop Details...done (0)
Find Visible Detail Sides...
Merged 172 detail faces...done (0)
Merging details...done (0)
FixTjuncs...
PruneNodes...
WriteBSP...
done (1)
writing C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.prt...Building visibility clusters...
done (0)
*** Error: Skybox vtf files for skybox/sky_alpinestorm_01 weren't compiled with the same size texture and/or same flags!
Can't load skybox file skybox/sky_alpinestorm_01 to build the default cubemap!
*** Error: Skybox vtf files for skybox/sky_alpinestorm_01 weren't compiled with the same size texture and/or same flags!
Can't load skybox file skybox/sky_alpinestorm_01 to build the default cubemap!
Finding displacement neighbors...
Finding lightmap sample positions...
Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
Building Physics collision data...
done (1) (169246 bytes)
Static prop models/props_trainyard/handrail128.mdl outside the map (456.00, -1012.00, 256.00)
Placing detail props : 0...1...2...3...4...5...6...7...8..Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
Material CP_MOUNTAINLAB/NATURE/GROUNDTOGRASS001 uses unknown detail object type tf_forest_grass!
.9...10
Water found with no water_lod_control entity, creating a default one.
Compacting texture/material tables...
Reduced 320 texinfos to 177
Reduced 31 texdatas to 25 (1124 bytes to 738)
Writing C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.bsp
Wrote ZIP buffer, estimated size 4821, actual size 3669
4 seconds elapsed
Valve Software - vvis.exe (Oct 14 2017)
2 threads
reading c:\program files (x86)\steam\steamapps\common\team fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.bsp
reading c:\program files (x86)\steam\steamapps\common\team fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.prt
 345 portalclusters
 890 numportals
BasePortalVis:       0...1...2...3...4...5...6...7...8...9...10 (0)
PortalFlow:          0...1...2...3...4...5...6...7...8...9...10 (15)
Optimized: 805 visible clusters (1.25%)
Total clusters visible: 64210
Average clusters visible: 186
Building PAS...
Average clusters audible: 340
visdatasize:32483  compressed from 33120
writing c:\program files (x86)\steam\steamapps\common\team fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.bsp
15 seconds elapsed
Valve Software - vrad.exe SSE (Oct 14 2017)

      Valve Radiosity Simulator     
2 threads
[Reading texlights from 'lights.rad']
unknown light specifier type - lights

[56 texlights parsed from 'lights.rad']

Loading c:\program files (x86)\steam\steamapps\common\team fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.bsp
Setting up ray-trace acceleration structure... Done (0.68 seconds)
1882 faces
809092 square feet [116509360.00 square inches]
20 Displacements
71014 Square Feet [10226090.00 Square Inches]
1882 patches before subdivision
58278 patches after subdivision
sun extent from map=0.258819
37 direct lights
BuildFacelights:     0...1...2...3...4...5...6...7...8...9...10 (34)
BuildVisLeafs:       0...1...2...3...4...5...6...7...8...9...10 (15)
transfers 4672990, max 371
transfer lists:  35.7 megs
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #1 added RGB(339493, 340902, 292726)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #2 added RGB(103138, 93887, 74531)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (1)
	Bounce #3 added RGB(37810, 32757, 23775)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #4 added RGB(15287, 12931, 8735)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #5 added RGB(6608, 5517, 3526)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (1)
	Bounce #6 added RGB(2974, 2454, 1503)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #7 added RGB(1375, 1119, 662)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #8 added RGB(646, 518, 297)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (1)
	Bounce #9 added RGB(307, 242, 135)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #10 added RGB(147, 113, 62)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #11 added RGB(71, 54, 28)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (1)
	Bounce #12 added RGB(34, 25, 13)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #13 added RGB(17, 12, 6)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (1)
	Bounce #14 added RGB(8, 6, 3)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #15 added RGB(4, 3, 1)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #16 added RGB(2, 1, 1)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (1)
	Bounce #17 added RGB(1, 1, 0)
Build Patch/Sample Hash Table(s).....Done<0.0695 sec>
FinalLightFace:      0...1...2...3...4...5...6...7...8...9...10 (6)
FinalLightFace Done
0 of 0 (0% of) surface lights went in leaf ambient cubes.
ThreadComputeLeafAmbient: 0...1...2...3...4...5...6...7...8...9...10 (17)
Writing leaf ambient...done
Ready to Finish

Object names       Objects/Maxobjs  Memory / Maxmem  Fullness 
------------       ---------------  ---------------  -------- 
models                  48/1024         2304/49152    ( 4.7%) 
brushes                491/8192         5892/98304    ( 6.0%) 
brushsides            3048/65536       24384/524288   ( 4.7%) 
planes                 998/65536       19960/1310720  ( 1.5%) 
vertexes              3409/65536       40908/786432   ( 5.2%) 
nodes                 1061/65536       33952/2097152  ( 1.6%) 
texinfos               177/12288       12744/884736   ( 1.4%) 
texdata                 25/2048          800/65536    ( 1.2%) 
dispinfos               20/0            3520/0        ( 0.0%) 
disp_verts            1620/0           32400/0        ( 0.0%) 
disp_tris             2560/0            5120/0        ( 0.0%) 
disp_lmsamples      155120/0          155120/0        ( 0.0%) 
faces                 1882/65536      105392/3670016  ( 2.9%) 
hdr faces                0/65536           0/3670016  ( 0.0%) 
origfaces             1253/65536       70168/3670016  ( 1.9%) 
leaves                1110/65536       35520/2097152  ( 1.7%) 
leaffaces             2297/65536        4594/131072   ( 3.5%) 
leafbrushes           1723/65536        3446/131072   ( 2.6%) 
areas                    2/256            16/2048     ( 0.8%) 
surfedges            14105/512000      56420/2048000  ( 2.8%) 
edges                 8551/256000      34204/1024000  ( 3.3%) 
LDR worldlights         37/8192         3256/720896   ( 0.5%) 
HDR worldlights          0/8192            0/720896   ( 0.0%) 
leafwaterdata            4/32768          48/393216   ( 0.0%) 
waterstrips            203/32768        2030/327680   ( 0.6%) 
waterverts               0/65536           0/786432   ( 0.0%) 
waterindices          3291/65536        6582/131072   ( 5.0%) 
cubemapsamples           4/1024           64/16384    ( 0.4%) 
overlays                11/512          3872/180224   ( 2.1%) 
LDR lightdata         [variable]     1263832/0        ( 0.0%) 
HDR lightdata         [variable]           0/0        ( 0.0%) 
visdata               [variable]       32483/16777216 ( 0.2%) 
entdata               [variable]       47744/393216   (12.1%) 
LDR ambient table     1110/65536        4440/262144   ( 1.7%) 
HDR ambient table     1110/65536        4440/262144   ( 1.7%) 
LDR leaf ambient      6753/65536      189084/1835008  (10.3%) 
HDR leaf ambient      1110/65536       31080/1835008  ( 1.7%) 
occluders                0/0               0/0        ( 0.0%) 
occluder polygons        0/0               0/0        ( 0.0%) 
occluder vert ind        0/0               0/0        ( 0.0%) 
detail props          [variable]           1/12       ( 8.3%) 
static props          [variable]           1/6682     ( 0.0%) 
pakfile               [variable]        3669/0        ( 0.0%) 
physics               [variable]      169246/4194304  ( 4.0%) 
physics terrain       [variable]        2546/1048576  ( 0.2%) 

Level flags = 0

Total triangle count: 5336
Writing c:\program files (x86)\steam\steamapps\common\team fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.bsp
1 minute, 19 seconds elapsed
C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\sourcesdk_content\tf\mapsrc\koth_mudlands_a2.bsp -> C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps\koth_mudlands_a2.bsp
1 File(s) copied
CompilePal - Cubemap Generator
Detecting HDR levels...
Map requires one set of cubemaps
Compiling cubemaps...
Cubemaps compiled

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\custom\
Found search path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf
Found search path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\bin
Found search path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\download
Reading BSP...
Initializing pak file...
Writing file list...
Running bspzip...
Finished!
---------------------
1 materials found
2 models found
0 particle files found
0 sounds found
additional files: 
---------------------

Valve Software - bspzip.exe (Oct 14 2017)
Warning: falling back to auto detection of vproject directory.
Repacking C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps\koth_mudlands_a2.bsp
Successfully repacked C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps\koth_mudlands_a2.bsp -- 2749076 -> 888086 bytes
'Normal - Pack' compile finished in 00:13:47
23 errors/warnings logged:
  23 errors/warnings logged for koth_mudlands_a2:
    ● 2x: Caution: Can't load skybox file [sub:1] to build the default cubemap!
    ● 1x: Info: Static prop [sub:1] outside the map ([sub:2], [sub:3], [sub:4])
    ● 20x: Caution: Material [sub:1] uses unknown detail object type [sub:2]! `

**Comment by maxdup** [comment]
well that's interesting, maybe deal with that outside of map prop to be safe in the future.
"Static prop models/props_trainyard/handrail128.mdl outside the map (456.00, -1012.00, 256.00)"

I'm going to close this issue for now, feel free to reopen if you can reproduce it
