### ISSUE TITLE
CompilePal does not pack scripts/ folder

### ISSUE THREAD

**Issue by ficool2** [ruarai/CompilePal#41]
I have a map with custom vehicle scripts, located in a folder like this: scripts/airboat.txt
CompilePal doesn't pack it into the bsp, which I need it to do. Can there be a fix for this?

Also to add, I'm making a map for Garry's mod, and in the TTT gamemode, a custom playermodel is referenced in an entity called ttt_map_settings. CompilePal does not pack the custom playermodel materials/models. Would it be possible to add some Pack feature by itself that will add the things needed without recompiling the map?

**Comment by maxdup** [comment]
Will gladly look into those, can you point me to the appropriate documentation for those scripts?

**Comment by ficool2** [comment]
No idea what you exactly mean by documentation, but for the vehicle script here is an example (it is a custom script used by a prop_vehicle_airboat entity to disable the guns and change controls slightly): https://www.dropbox.com/s/5kjiy2wzrntsh43/compilepalexample.zip?dl=1 . CompilePal refuses to add this scripts/vehicles/ folder into the bsp.

For the player models, I doubt you will be able to find the appropriate materials for the models referenced in the ttt_map_settings unless you have some form of model viewer (it's not loaded into Hammer, its loaded in-game). Therefore a separate PACK feature just like Pakrat or VIDE would be better, and it would also solve the issue with vehicle scripts not being added, as they can be added manually

**Comment by maxdup** [comment]
Okay, I've just implemented support for vehicle scripts. Custom player models for ttt are going to be detected.

I've created a separate feature request to add files on top of the current asset detection. https://github.com/ruarai/CompilePal/issues/44 check it out and discuss that feature there if you have something to add to that.

I'll be closing this issue now. thanks for reporting.
