### ISSUE TITLE
Program won't luanch. 

### ISSUE THREAD

**Issue by CVRP-Andromeda** [ruarai/CompilePal#42]
CompilePal crashes on launch. I have disabled my AA, I have tried it with comparability mode. That too has not worked. It simply opens, a blank window which says "game selection". Then crashes. Please help. Thanks a lot! - Andromeda

**Comment by maxdup** [comment]
Have you tried a freshly downloaded build? That could clear up potential configuration issues.
Also do you happen to have a "CrashLogs" folder in your compilepal folder? if so, send anything you find in there our way.

**Comment by CVRP-Andromeda** [comment]
Nope. No crash folder. And I have tried an older version. And redownloaded
the program twice. Even onto separate drives.

**Comment by JesseB1f** [comment]
I am having the same problem, but I do have a crash log:
System.NullReferenceException: Object reference not set to an instance of an object.
   at CompilePalX.GameConfigurationParser.Parse(String filename)
   at CompilePalX.LaunchWindow..ctor()

**Comment by Exactol** [comment]
What version of Compile Pal are you running and what game are you trying to compile for? can you send the GameConfig.txt from the bin folder of the game you are compiling for?

**Comment by JesseB1f** [comment]
I am running the latest version, 026, and here is the GameConfig.txt from my version of Team Fortress 2:
"GameConfig.txt"
{
	"Games"
	{
		"Half-Life 2"
		{
			"GameDir"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\hl2"
			"Hammer"
			{
				"GameData0"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\halflife2.fgd"
				"TextureFormat"		"5"
				"MapFormat"		"4"
				"DefaultTextureScale"		"0.250000"
				"DefaultLightmapScale"		"16"
				"GameExe"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\hl2.exe"
				"DefaultSolidEntity"		"func_detail"
				"DefaultPointEntity"		"info_player_start"
				"BSP"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\vbsp.exe"
				"Vis"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\vvis.exe"
				"Light"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\vrad.exe"
				"GameExeDir"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2"
				"MapDir"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\sourcesdk_content\hl2\mapsrc"
				"BSPDir"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\hl2\maps"
				"CordonTexture"		"tools\toolsskybox"
				"MaterialExcludeCount"		"0"
			}
		}
		"Team Fortress 2"
		{
			"GameDir"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf"
			"Hammer"
			{
				"GameData0"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\tf-abs.fgd"
				"TextureFormat"		"5"
				"MapFormat"		"4"
				"DefaultTextureScale"		"0.250000"
				"DefaultLightmapScale"		"16"
				"GameExe"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\hl2.exe"
				"DefaultSolidEntity"		"func_detail"
				"DefaultPointEntity"		"prop_static"
				"BSP"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\vbsp.exe"
				"Vis"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\vvis.exe"
				"Light"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\vrad.exe"
				"GameExeDir"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2"
				"MapDir"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\sourcesdk_content\tf\mapsrc"
				"BSPDir"		"C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\maps"
				"CordonTexture"		"tools\toolsskybox"
				"MaterialExcludeCount"		"0"
			}
		}
	}
	"SDKVersion"		"5"
}

**Comment by Exactol** [comment]
Can you try downloading the latest pre-release and see if it still crashes?

**Comment by JesseB1f** [comment]
I'm not sure how it's different, but version 026.2 opened for me. Thanks for the advice!

**Comment by Exactol** [comment]
@CVRP-Andromeda I know this thread is almost 2 years old, but does this solve your issue as well?

**Comment by Exactol** [comment]
Closing stale issues
