### ISSUE TITLE
Compile Pal doesn't pack sounds using special operators

### ISSUE THREAD

**Issue by GeorgeRiley** [ruarai/CompilePal#46]
In soundscripts/soundscapes? (not sure about this one with #)/ambient_generic sounds
theres 2 special operators/prefixes that can be added to sounds:
'\*' forces the sound to precache at the start of the map (and is required for mp3s in CS:GO iirc)
'#' makes the sound obey the music volume slider in CS:S and other related games.
While I haven't tested '*' Compile Pal will currently not pack ambient_generics with the '#' operator, and (I assume) it won't pack soundscripts/scapes using the same operator.

**Comment by maxdup** [comment]
I will be taking care of that thanks

**Comment by GeorgeRiley** [comment]
Just looked at the code, and you seem to have missed that the '\*' and '\#' operators work within ambient_generic entities meaning these currently don't get automatically packed in compile pal.

**Comment by maxdup** [comment]
ah yes you're right, I only implemented the operators for soundscapes and soundscripts. Thanks for pointing that out.

**Comment by maxdup** [comment]
Should be fixed for good now, we'll try to get v26 out soonish (valve time).
c664be5
