### ISSUE TITLE
Compilepal crashes on startup

### ISSUE THREAD

**Issue by sharktemplar** [ruarai/CompilePal#48]
I had this program working previously, but then began a free trial of Avast, and now all of a sudden the program crashes upon startup. I was under the impression Avast found compilepal suspicious and blocked elements required for it to start, so I uninstalled avast completely and tried to run compilepal, but it had the same result. I tried running compilepal as administrator, same result. Redownloaded 025.zip entirely and extracted it to a different location. Same result. 
I'm stumped and I need compilepal for a project I'm doing. Does anybody know what I might have done that has seemingly broken compilepal for me entirely? Where can I check to see what's causing this crash?

**Comment by ruarai** [comment]
Honestly this is a very weird issue. There's not many things that can really cause this.

There are sometimes crash logs in the 'CrashLogs' folder in the compile pal directory. If there is one, copy it over here and I'll have a look.

If that isn't possible, try running this:
https://www.raymond.cc/blog/download/did/1741/

It should be able to make sure your .NET is up to date (version 4.7).

**Comment by sharktemplar** [comment]
I find no crashlogs folder in the compilepal directory, or any crashlog text files of any kind. Just version.txt and debug.txt.
The NET detector confirms I have 4.7.1
Is it possible windows 7 was somehow told by avast to permanently consider compilepal.exe a threat and block all programs of this name from functioning? I really can't understand how else this would happen even after uninstalling avast and trying it again. Is it some niche little thing where I was correct in uninstalling avast but had to redownload compilepal WHILE avast was uninstalled, which I didn't do?

**Comment by ruarai** [comment]
That's interesting, good to hear it's fixed at least.

There's a lot of complexity behind the scenes that Compile Pal might be depending on so there's so many things that could have caused it.

Let me know if there's any future issues.
