### ISSUE TITLE
This useless box that seems like a text box.

### ISSUE THREAD

**Issue by Ewber** [ruarai/CompilePal#55]
![useless box](https://user-images.githubusercontent.com/31393813/43674686-6f34d39a-981b-11e8-8ecc-f13e925e4dc9.PNG)
For some strange reason when I try and click on the box it does nothing, im trying to make the copy function copy the bsp to my mod's maps folder, but it seems like I cant do it. Is this a glitch?

**Comment by Exactol** [comment]
The text box is just a preview for the parameters of that process. If you wanted to add a parameter, you would click the add... button to the right of the text box. If you are trying to copy to a custom location, I don't think there's currently support for that. By default, copy will copy to the game's map folder.

**Comment by ruarai** [comment]
I believe you should be able to modify the game configuration json file and
change the map folder location if you need. It’s a seperate value so it
shouldn’t matter if it’s outside the normal game folder.
