### ISSUE TITLE
Soundscapes

### ISSUE THREAD

**Issue by MAGNAT2645** [ruarai/CompilePal#56]
Autopack doesn't scan for "scripts/soundscapes_[mapname].txt" sound files, but works fine with "maps/[mapname]_level_sounds.txt".

EDIT: I saw that CompilePal supports soundscapes but doesn't scan for my tf/custom/mymaps/scripts folder.
Game is TF2 as you can see.

**Comment by Exactol** [comment]
Can you post your debug.log? I just tested this out and it worked for me, so it might be an issue that has been resolved already.

**Comment by MAGNAT2645** [comment]
debug.log said that CompilePal found soundscape script but it doesnt pack sounds from script

> ---------------------
> 276 materials found
> 17 models found
> 0 particle files found
> 34 sounds found
> additional files: 
> -nav file
> -soundscape
> -soundscript
> ---------------------

Also there was error when i tried to autopack already compiled map (with disabled VBSP, VRAD, VVIS in CompilePal)

> CompilePal - Automated Packaging
> Finding sources of game content...
> Found search paths...
> Found wildcard path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\custom\
> Found search path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf
> Found search path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\bin
> Found search path: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\download
> Reading BSP...
> Something broke:
> System.IndexOutOfRangeException: Index was outside the bounds of the array
>    in CompilePalX.Compilers.BSPPack.BSP.buildEntityList()
>    in CompilePalX.Compilers.BSPPack.BSP..ctor(FileInfo file)
>    in CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context)

**Comment by MAGNAT2645** [comment]
I don't remember because it was 11 days ago since map release. I will try again to autopack other map.

**Comment by MAGNAT2645** [comment]
Yeah, alpha build works fine. Soundscape was found inside custom/ folder and packed into BSP.

Can you add parameter that can put custom launch params into GAME process?
Also, would be good if CompilePal was able to delete original .nav file after renaming it to embed.nav and autopacking /graphs/(mapname).ain would be good too.
