### ISSUE TITLE
Issue packing model collisions

### ISSUE THREAD

**Issue by csWaldo** [ruarai/CompilePal#58]
For some reason compile pal won't pack my custom models collision files. The collisions work and are turned on in hammer. The .phy file has the same name as the rest of the model files and sits in the same folder. Compile pal packs the model without any issue, error or warning and the files are correctly packed and working except for the .phy file.
I've tried with renaming and recompiling the map, running as admin and using other peoples custom props that compile pal manages to pack just fine into their levels. Whatever or whenever I pack, the model collisions won't be included. I tried packing with VIDE and its auto function finds and packs the collision files without any trouble.

I'm really at a loss here.

Edit:
Had someone pack the same files and it worked for them. I tried multiple versions of compile pal including the one he used that worked for him and the collisions still wont pack. :(

Edit 2:
I tried anything that comes to mind but can't get it to pack the .phy files. The files.txt correctly shows their origin and target paths but somehow compile pal won't add them to the bsp when packing without throwing any errors.

**Comment by Exactol** [comment]
What game are you targeting and can you paste the contents of the debug.log file?

**Comment by csWaldo** [comment]
CS:GO, this is the debug.log with a failed pack: https://pastebin.com/HPJ9DMau
Compile Pal doesn't seem to be the actual issue. I'm the only user experiencing this problem. The files.txt points to the correct files. Calling bspzip by hand using files.txt as the list packs the collision models correctly. When running pack with verbose, it lists the collision files as "adding <file path>", they just dont show up in my bsp. Very rarely, they will show up in the bsp. Its very strange.

Compile pal finds the dependencies correctly. Calling bspzip through a bat packs the bsp correctly.
Right now I'm just trying to figure out how to have Compile Pal call a .bat with the bsp and list file paths as parameters so I can just run Pack with -dryrun and then that .bat automatically to pack my level.

**Comment by Exactol** [comment]
If you compile Compile Pal from the source code, there is now support for custom programs with the Custom process. Some other possible fixes could be making sure that you don't have the BSP open in any program when it gets packed, or trying a fresh install of Compile Pal.

**Comment by csWaldo** [comment]
Yeah, those are some of the first things I tried. I'm trying to use the custom option, I just can't figure out how to pass the bsp path of the current file along as a parameter.

**Comment by Exactol** [comment]
You can use all of the hammer expert parameters as command line arguments. https://developer.valvesoftware.com/wiki/Hammer_Run_Map_Expert#Parameters.
To get the path of the bsp, you can use $bspdir\$file.bsp in the command line argument input.  I plan on writing a tutorial on this in the future.

**Comment by csWaldo** [comment]
Sorry, but am I missing something? It's just passing it along as a string:
https://i.imgur.com/q7F53fP.png
https://i.imgur.com/q9bhla1.png

**Comment by Exactol** [comment]
Is this newly compiled?

**Comment by csWaldo** [comment]
No, I'm currently using this version: https://github.com/gortnarj/CompilePal/releases/tag/v025
Yanzl added some extra dependencies for cs go as far as I know. I don't know if these changes are in the official branch? I don't know how to compile a current version.

Sorry for stealing your time.

**Comment by Exactol** [comment]
It looks like it's actually broken right now, since $bspdir$file.bsp will result in "programpath\""map".bsp which is not valid for most programs. I'm working on a fix.

**Comment by csWaldo** [comment]
Yes, that works! Took me some time to get the formatting right, but I managed it. Thank you so much.

Not sure if its a known issue, but cloning or deleting a config with custom in it will crash pal. The clone or delete still works though.

Edit: just read your last post, and yes. I did the formatting inside the bat. That works well enough.

**Comment by Exactol** [comment]
Did not know about that crash, thanks for the heads up.

**Comment by csWaldo** [comment]
I've narrowed my issue down to this: When Compile Pal calls bspzip.exe, it correctly tells it to pack the .phy files, but somehow, it wont. Doesn't matter wether I call bspzip.exe through a .bat or the pack option. As long as Pal calls it, it won't pack collisions. Giving both Pal and bspzip admin permissions does not change this.

I'll just use Pal to create the files.txt and then call bspzip manually through a .bat file. If youve got any idea how I could fix my issue, please let me know. Otherwise I'll just use my workaround. It's just a few extra clicks anyways.

Thanks again for all the help!

**Comment by Exactol** [comment]
Have you tried verifying your game cache?

**Comment by csWaldo** [comment]
I made a clean install of the game not long ago, but verified anyways. No luck.
My best guess would be some sort of permission error? Calling bspzip manually works. Compile Pal creates the file list correctly. It's just when calling bspzip through pal that fails to pack the .phy files.
No idea how to adress that though other than running everything as admin. And that didn't help either. Really strange stuff.

**Comment by maxdup** [comment]
I can confirm that compilepal doesn't even touch phy files (to read them or whatever). Compilepal only checks that the file exists (and it does exist if it made it into files.txt) so I don't think this could be a "file is in use" by compilepal type of deal. Which leaves very little explanations. This is so super perplexing.

**Comment by Exactol** [comment]
Closing stale issues
