### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by EwDirt** [ruarai/CompilePal#61]
Tried several .net builds and I can't seem to get around this error.

Starting

 a 'Fast' compile.
Starting compilation of rp_guam_alpha_001 - Copy

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod\addons\
Found search path: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod\bin
Found search path: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod\download
Reading BSP...
Something broke:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at CompilePalX.Compilers.BSPPack.BSP.buildModelList()
   at CompilePalX.Compilers.BSPPack.BSP..ctor(FileInfo file)
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context)
'Fast' compile finished in 00:00:00
0 errors/warnings logged:
  No errors/warnings logged for rp_guam_alpha_001 - Copy

**Here is the full compile log.**

 Starting

 a 'Fast' compile.
Starting compilation of rp_guam_alpha_001 - Copy
Valve Software - vbsp.exe (Oct  3 2018)
8 threads
materialPath: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod\materials
Loading D:\Dropbox\Source SDK\VMFs\Gmod\rp_guam_alpha_001 - Copy.vmf
Can't find surfaceprop sheetrock for material PLASTER/WALL_GREY01_SSBUMP, using default
Can't find surfaceprop sheetrock for material PLASTER/CEILING_POPCORN02, using default
Can't find surfaceprop sheetrock for material PLASTER/PLASTER_CEILING_03, using default
ConVarRef mat_reduceparticles doesn't point to an existing ConVar
Can't find surfaceprop sheetrock for material PLASTER/PLASTER_INT_15A, using default
Can't find surfaceprop sheetrock for material PLASTER/PLASTER_INT_18, using default
Can't find surfaceprop asphalt for material CONCRETE/ROADPARKINGLOT, using default
Can't find surfaceprop panel for material METAL/PRODVENTA, using default
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/custom/ewdirt/minecraft.vmt
LightmappedGeneric, (*Proxies*), (*MaterialModifyAnimated*),
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/custom/ewdirt/minecraft.vmt
LightmappedGeneric, (*Proxies*), (*MaterialModifyAnimated*),
Could not locate 'GameData' key in g:\programs-g\steam\steamapps\common\garrysmod\garrysmod\gameinfo.txt
Patching WVT material: maps/rp_guam_alpha_001 - copy/concrete/blend_concrete_01_wvt_patch
Patching WVT material: maps/rp_guam_alpha_001 - copy/nature/blendsandsand008a_wvt_patch
Patching WVT material: maps/rp_guam_alpha_001 - copy/nature/blendmuddirt001a_wvt_patch
fixing up env_cubemap materials on brush sides...
Multiple references for cubemap on texture maps/rp_guam_alpha_001 - copy/nature/water_riverbed02_6159_-3722_92!!!
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/CUSTOM/EWDIRT/MINECRAFT.vmt
LightmappedGeneric, (*Proxies*), (*MaterialModifyAnimated*),
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/CUSTOM/EWDIRT/MINECRAFT.vmt
LightmappedGeneric, (*Proxies*), (*MaterialModifyAnimated*),
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/CUSTOM/EWDIRT/MINECRAFT.vmt
LightmappedGeneric, (*Proxies*), (*MaterialModifyAnimated*),
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/CUSTOM/EWDIRT/MINECRAFT.vmt
LightmappedGeneric, (*Proxies*), (*MaterialModifyAnimated*),
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial! Ignoring...
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (1)
ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
Processing areas...done (0)
Building Faces...done (1)
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Occluder "" straddles multiple areas. This is invalid!
Chop Details...done (0)
Find Visible Detail Sides...
Merged 1228 detail faces...done (0)
Merging details...done (1)
FixTjuncs...
PruneNodes...
WriteBSP...
done (2)
writing D:\Dropbox\Source SDK\VMFs\Gmod\rp_guam_alpha_001 - Copy.prt...Building visibility clusters...
done (0)
Creating default LDR cubemaps for env_cubemap using skybox materials:
   skybox/sky40*.vmt
 ! Run buildcubemaps in the engine to get the correct cube maps.
Creating default HDR cubemaps for env_cubemap using skybox materials:
   skybox/sky40*.vmt
 ! Run buildcubemaps in the engine to get the correct cube maps.
Finding displacement neighbors...
Finding lightmap sample positions...
Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
Building Physics collision data...
WARNING: Map using power 4 displacements, terrain physics cannot be compressed, map will need additional memory and CPU.
done (2) (3279750 bytes)
Error loading studio model "models/props/cs_office/light_inset.mdl"!
Error loading studio model "models/props/cs_assault/wirespout.mdl"!
Static prop models/props_wasteland/boat_fishing01a.mdl outside the map (12915.00, -2646.00, 246.00)
Error loading studio model "models/props/cs_assault/light_shop2.mdl"!
Error loading studio model "models/props/de_inferno/hr_i/gutters/gutters_128.mdl"!
Error loading studio model "models/props/de_train/de_train_gutter_01.mdl"!
Error loading studio model "models/props_downtown/sign_stop.mdl"!
Error loading studio model "models/props/cs_militia/trees3.mdl"!
Error loading studio model "models/props/cs_militia/boulderring01.mdl"!
Error loading studio model "models/props_foliage/swamp_grass01.mdl"!
Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
Compacting texture/material tables...
Reduced 19884 texinfos to 7244
Reduced 1369 texdatas to 1215 (69335 bytes to 63458)
Writing D:\Dropbox\Source SDK\VMFs\Gmod\rp_guam_alpha_001 - Copy.bsp
17 seconds elapsed
Valve Software - vvis.exe (Oct  3 2018)
fastvis = true
nosort = true
8 threads
reading d:\dropbox\source sdk\vmfs\gmod\rp_guam_alpha_001 - Copy.bsp
reading d:\dropbox\source sdk\vmfs\gmod\rp_guam_alpha_001 - Copy.prt
4082 portalclusters
13363 numportals
BasePortalVis:       0...1...2...3...4...5...6...7...8...9...10 (8)
Optimized: 1402267 visible clusters (12.52%)
Total clusters visible: 11203034
Average clusters visible: 2744
Building PAS...
Average clusters audible: 4012
visdatasize:3766672  compressed from 4179968
writing d:\dropbox\source sdk\vmfs\gmod\rp_guam_alpha_001 - Copy.bsp
11 seconds elapsed
Valve Software - vrad.exe SSE (Oct  3 2018)
 
      Valve Radiosity Simulator    
8 threads
[Reading texlights from 'lights.rad']
[45 texlights parsed from 'lights.rad']
 
Loading d:\dropbox\source sdk\vmfs\gmod\rp_guam_alpha_001 - Copy.bsp
Error! Invalid VTX file checksum: 2008596908, expected -2083535301 "models/props/cs_office/light_ceiling.dx80.vtx"
Setting up ray-trace acceleration structure... Done (2.65 seconds)
22937 faces
14 degenerate faces
3071719 square feet [442327552.00 square inches]
13 Displacements
256556 Square Feet [36944192.00 Square Inches]
22923 patches before subdivision
22923 patches after subdivision
sun extent from map=0.000000
sun extent from map=0.000000
sun extent from map=0.000000
579 direct lights
BuildFacelights:     0...1...2...3...4...5...6...7...8...9...10 (73)
BuildVisLeafs:       0...1...2...3...4...5...6...7...8...9...10 (23)
transfers 4459853, max 2228
transfer lists:  34.0 megs
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
    Bounce #1 added RGB(175836, 156210, 127849)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
    Bounce #2 added RGB(37571, 29881, 21664)
Build Patch/Sample Hash Table(s).....Done<0.1068 sec>
FinalLightFace:      0...1...2...3...4...5...6...7...8...9...10 (9)
FinalLightFace Done
Computing detail prop lighting : 0...1...2...3...4...5...6...7...8...9...10
63 of 85 (74% of) surface lights went in leaf ambient cubes.
ThreadComputeLeafAmbient: 0...1...2...3...4...5...6...7...8...9...10 (29)
Writing leaf ambient...done
Ready to Finish
 
Object names       Objects/Maxobjs  Memory / Maxmem  Fullness
------------       ---------------  ---------------  --------
models                 512/1024        24576/49152    (50.0%)
brushes               8121/8192        97452/98304    (99.1%) VERY FULL!
brushsides           58756/65536      470048/524288   (89.7%) VERY FULL!
planes               35290/65536      705800/1310720  (53.8%)
vertexes             44989/65536      539868/786432   (68.6%)
nodes                13044/65536      417408/2097152  (19.9%)
texinfos              7244/12288      521568/884736   (59.0%)
texdata               1215/2048        38880/65536    (59.3%)
dispinfos               13/0            2288/0        ( 0.0%)
disp_verts            1677/0           33540/0        ( 0.0%)
disp_tris             2816/0            5632/0        ( 0.0%)
disp_lmsamples      150169/0          150169/0        ( 0.0%)
faces                22937/65536     1284472/3670016  (35.0%)
hdr faces                0/65536           0/3670016  ( 0.0%)
origfaces            16388/65536      917728/3670016  (25.0%)
leaves               13557/65536      433824/2097152  (20.7%)
leaffaces            30061/65536       60122/131072   (45.9%)
leafbrushes          18116/65536       36232/131072   (27.6%)
areas                   30/256           240/2048     (11.7%)
surfedges           180491/512000     721964/2048000  (35.3%)
edges               120841/256000     483364/1024000  (47.2%)
LDR worldlights        577/8192        50776/720896   ( 7.0%)
HDR worldlights          0/8192            0/720896   ( 0.0%)
leafwaterdata            6/32768          72/393216   ( 0.0%)
waterstrips           3109/32768       31090/327680   ( 9.5%)
waterverts               0/65536           0/786432   ( 0.0%)
waterindices         59439/65536      118878/131072   (90.7%) VERY FULL!
cubemapsamples         203/1024         3248/16384    (19.8%)
overlays               137/512         48224/180224   (26.8%)
LDR lightdata         [variable]    11144696/0        ( 0.0%)
HDR lightdata         [variable]           0/0        ( 0.0%)
visdata               [variable]     3766672/16777216 (22.5%)
entdata               [variable]     1380721/393216   (351.1%) VERY FULL!
LDR ambient table    13557/65536       54228/262144   (20.7%)
HDR ambient table    13557/65536       54228/262144   (20.7%)
LDR leaf ambient     37466/65536     1049048/1835008  (57.2%)
HDR leaf ambient     13557/65536      379596/1835008  (20.7%)
occluders                2/0              80/0        ( 0.0%)
occluder polygons       16/0             192/0        ( 0.0%)
occluder vert ind       64/0             256/0        ( 0.0%)
detail props          [variable]           1/89624    ( 0.0%)
dtl prp lght          [variable]           1/4        (25.0%)
HDR dtl prp lght      [variable]           1/4        (25.0%)
static props          [variable]           1/42010    ( 0.0%)
pakfile               [variable]    17040069/0        ( 0.0%)
physics               [variable]     3279750/4194304  (78.2%)
physics terrain       [variable]           0/1048576  ( 0.0%)
 
Level flags = 0
 
Total triangle count: 69158
Writing d:\dropbox\source sdk\vmfs\gmod\rp_guam_alpha_001 - Copy.bsp
2 minutes, 17 seconds elapsed
CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod\addons\
Found search path: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod\bin
Found search path: G:\Programs-G\Steam\steamapps\common\GarrysMod\garrysmod\download
Reading BSP...
Something broke:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at CompilePalX.Compilers.BSPPack.BSP.buildModelList()
   at CompilePalX.Compilers.BSPPack.BSP..ctor(FileInfo file)
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context)
'Fast' compile finished in 00:02:48
30 errors/warnings logged:
  30 errors/warnings logged for rp_guam_alpha_001 - Copy:
    ● 6x: Caution: KeyValues Error: RecursiveLoadFromBuffer: got EOF instead of keyname in file [sub:1]
    ● 13x: Info: Material glass/glasswindowbreak070b is depending on itself through materialvar $crackmaterial!
    ● 9x: Caution: Error loading studio model &quot;[sub:1]&quot;!
    ● 1x: Info: Static prop [sub:1] outside the map ([sub:2], [sub:3], [sub:4])
    ● 1x: Info: fastvis = true

**Comment by maxdup** [comment]
Well, well, from the error, it seems you're running out of RAM and it seems to have done so while loading models from your map. So how much RAM do you have? Could be that you don't have sufficent ram to run this map, could be that there is an error in CompilePal that makes it take too much ram, could be that one of your models is faulty. My advice would be to try and deal with vbsp's "Caution: Error loading studio model" errors and then we can narrow it down somewhat.

**Comment by EwDirt** [comment]
From further troubleshooting it seems to be a non-issue on CompilePal's end. I will do a full Windows reinstall in the future and open a new ticket if the problem persists.
