### ISSUE TITLE
V26 Release

### ISSUE THREAD

**Issue by Exactol** [ruarai/CompilePal#62]
It's been over a year since V25 was released, and I'm thinking it's almost time to release the next version. Since I'm new to the project, I don't really know what the process of releasing a new version entails. If you guys agree that it's time for a release, what steps can I do to help get the process started.

**Comment by ruarai** [comment]
I don't really interact with this project anymore so I'm guessing @maxdup has more of an opinion of if it's ready to release.

But the release process is pretty simple - just compile a build in 'Release' configuration, delete any unnecessary files (just look at previous releases to check what that is exactly) and archive that in a zip file.

You can then upload the zip file to the Releases section on GitHub, following the format of previous releases, so a tag of v026, a changelog, etc. Not that any of that really matters - just need to make sure there's a file uploaded.

The update checker works based on the version.txt file here: https://github.com/ruarai/CompilePal/blob/master/CompilePalX/version.txt
Increment this once the release is uploaded.

Really appreciate what you've done so far for the project. I've definitely lost interest/time a while ago, so good to see that someone is still keeping it updated. Just looking at the analytics - there's 336 monthly unique users, so the work of you, maxdup and others definitely isn't going to waste.

**Comment by CaskoChan** [comment]
When will V26 be released?

**Comment by Exactol** [comment]
V26 should hopefully be released soon, I'm just finishing fixing a few bugs. As for packing from VPKs, it's currently not planned. I'm not sure how to differentiate stock vpks from custom vpks.

**Comment by CaskoChan** [comment]
You could allow the user to select the vpk or vpks to be scanned and have content extracted from the selected vpks. This feature would be really helpful since having lose files just messy and hammer takes its sweet time loading modles since there lose files. I'm very excited for v26 thank you for your teams hard work on this tool.

**Comment by RuFFle23** [comment]
If anyone can help me, it'd be appreciated.

4 days ago I've installed Filmora (video-editing program) and a youtube mp3 converter(FLVTO).
Ever since I've downloaded these and after restarting the computer, compilepal refuses to start without any error message or any message at all, it just simply offers me the option for tf2 or hl2. After clicking one of those it just crashes and I can't seem to find any crash-log folder. One more thing to point out is that after downloading these programs, avast popped up without me downloading it, assuming the compilepal crash has any corellation with avast I proceeded to deinstall avast with the apps&features option in hopes to resolve the problem (assumingly caused by avast). Avast was succsessfully deinstalled, but compilepal still proceeded not to work. 

If anyone knows if avast has any correlation to the cause of not starting compilepal or if anyone is able to help me, I'd be greatly appreciated. Thanks!

**Comment by Exactol** [comment]
Have you tried reinstalling CompilePal?

**Comment by CaskoChan** [comment]
@Exactol do you think, instead of that vpk feature l, what if, we could have an option to select a separate folder to be scanned for content instead of having lose files in the game directory? It's just like how VIDE scans folders you tell it to scan for stuff. Hope this is possible

**Comment by CaskoChan** [comment]
@Exactol When will v26 come, i hate pestering you but i really need v26 because i think it will make packing much easier.

**Comment by Exactol** [comment]
@CaskoChan soon™. In the mean time feel free to use a beta build.
[CompilePal 026Beta1.8.zip](https://github.com/ruarai/CompilePal/files/3129868/CompilePal.026Beta1.8.zip)

**Comment by CaskoChan** [comment]
> @CaskoChan soon™. In the mean time feel free to use a beta build.
> [CompilePal 026Beta1.8.zip](https://github.com/ruarai/CompilePal/files/3129868/CompilePal.026Beta1.8.zip)
> 
> In reference to the VPK packing, I will consider looking into it for V27, but I don't have a lot of free time anymore, so it might be a while

Thank you very much for all you work on this tool. i tried out that beta build you linked, i keep getting this error 

System.NullReferenceException: Object reference not set to an instance of an object.
   at CompilePalX.GameConfigurationParser.Parse(String filename) in C:\Users\10zil\OneDrive\Documents\Visual Studio 2017\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\GameConfigurationParser.cs:line 143
   at CompilePalX.LaunchWindow..ctor() in C:\Users\10zil\OneDrive\Documents\Visual Studio 2017\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\LaunchWindow.xaml.cs:line 58

**Comment by Exactol** [comment]
@CaskoChan What game are you trying to compile for

**Comment by CaskoChan** [comment]
> @CaskoChan What game are you trying to compile for
Its not even when i try to compile a map,i get that error when i try launching the program.

**Comment by Exactol** [comment]
What game were you going to try to compile for before it crashed

From,
Zach Matuson

**Comment by CaskoChan** [comment]
> What game were you going to try to compile for before it crashed From, Zach Matuson
> […](#)
> On Apr 30, 2019, at 3:27 PM, Casko ***@***.***> wrote: @CaskoChan What game are you trying to compile for Its not even when i try to compile a map,i get that error when i try launching the program. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Oh it was source 2013 MP

**Comment by Exactol** [comment]
Can you send me your gameconfig.txt file?

**Comment by CaskoChan** [comment]
> Can you send me your gameconfig.txt file?

HAHAHAA, god im such a brainlet. I just deleted the gameconfig that came with your zip and now it works. Sorry about the confusion.

**Comment by CaskoChan** [comment]
After further attempts at trying to get the beta version you uploaded, it still won't launch, and I get the same error i posted earlier everytime I try to open the executable

**Comment by Exactol** [comment]
Can you send me the gameConfigs.json inisde the CompilePal/GameConfiguration folder, and can you send me the gameinfo.txt located somewhere in the directory of the game you are trying to compile for

**Comment by CaskoChan** [comment]
[gameinfo.txt](https://github.com/ruarai/CompilePal/files/3163762/gameinfo.txt)

https://drive.google.com/file/d/1wXB1Iopr0eqtPshl_KI6u6lSv44UMDN3/view?usp=sharing

**Comment by Exactol** [comment]
You can now follow progress to the V26 release on https://github.com/ruarai/CompilePal/projects/1

**Comment by Exactol** [comment]
V26 is finally out!
