### ISSUE TITLE
No warning when compiling without steam

### ISSUE THREAD

**Issue by snake-biscuits** [ruarai/CompilePal#63]
TF2 can't load maps when steam isn't running, rendering cubemaps & any other compile options that require the game to be active useless.

You don't have to turn steam on for the user, just throwing up a "Steam is not running, are you sure you want to compile?" warning / alert would be enough imo

**Comment by DaSpudLord** [comment]
Hello snakebiscuits,

Recently CompilePal released a new beta version with the option to execute your own programs and files during a compile. I created a script that will automatically check to see if Steam is running, and will launch it if not. See here: https://tf2maps.net/posts/453521/

Hopefully this will fix your issue.
