### ISSUE TITLE
'Publish' setting generates a fullbright map

### ISSUE THREAD

**Issue by Aspect12** [ruarai/CompilePal#67]
Title.
No idea why.

**Comment by lokkdokk** [comment]
The same shit with Final (both) compile.

**Comment by Exactol** [comment]
This is probably because Publish has only HDR enabled in the VRAD step. I think it's setup like this since Compile Pal was originally made with CS:GO in mind. To fix it, just add -both or -ldr to the VRAD step.

**Comment by Aspect12** [comment]
How would I go about doing that? Quite new to CompilePal, so I'm not super familiar with it just yet.
