### ISSUE TITLE
Stuck on "PortalFlow: 0"

### ISSUE THREAD

**Issue by Aspect12** [ruarai/CompilePal#71]
No matter the map, it always gets stuck on "PortalFlow:          0". It just started doing it one day. The program doesn't even freeze. It just sits there. Should I just reinstall it or something?

**Comment by Exactol** [comment]
Are you sure it's not your map that's freezing the compile? Have you tried compiling it through hammer and seeing if it will go past PortalFlow: 0?

**Comment by Aspect12** [comment]
Update, I reinstalled, problem still occurs.

**Comment by Aspect12** [comment]
I tried compiling with HL2 instead of Garry's Mod and it moved along fine. That means Garry's Mod is causing a problem. Why though..

**Comment by Aspect12** [comment]
Alright, update:
I just found out that the "VBSPInfo" and "SDKMapFolder" files do not exist. I'll try using the HL2 ones instead.

**Comment by Aspect12** [comment]
Alright, I've fixed it! I reinstalled the vbsp, vvis and vrad files and then it worked. Thanks for the help anyways!
