### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by Exactol** [ruarai/CompilePal#72]
Moved to new issue to avoid clogging up the release thread.

[gameinfo.txt](https://github.com/ruarai/CompilePal/files/3163762/gameinfo.txt)

https://drive.google.com/file/d/1wXB1Iopr0eqtPshl_KI6u6lSv44UMDN3/view?usp=sharing

_Originally posted by @CaskoChan in https://github.com/ruarai/CompilePal/issues/62#issuecomment-491045758_

**Comment by Exactol** [comment]
Can you try deleting your gameconfig.json and restarting CompilePal?

**Comment by CaskoChan** [comment]
That gameconfig.json was from a beta you posted on the tf2 forums I think. Because, your latest build, doesnt generate a gameconfig.json . When I get home from work today, I'll give it a go and let you know if anything changes

**Comment by CaskoChan** [comment]
Nope still get the same error, even when i deleted the gameconfiguration.json 

[debug.log](https://github.com/ruarai/CompilePal/files/3170560/debug.log)

[2019-05-12T17-01-13.txt](https://github.com/ruarai/CompilePal/files/3170561/2019-05-12T17-01-13.txt)

**Comment by CaskoChan** [comment]
Any update on this issue?

**Comment by CaskoChan** [comment]
@Exactol i dont know how to compile github projects, so if you post development builds after you make commits, thats would be cool. Again thanks for all your work.

**Comment by Exactol** [comment]
The plan for dev builds after V26 is to post them in the downloads section, but marked as pre-release. Might look into adding some kind of continuous integration to automatically compile and post a pre-release for each commit. 

For now, I'll post updates builds here @CaskoChan .

**Comment by CaskoChan** [comment]
Sounds good.

**Comment by Exactol** [comment]
Actually just realized that I asked for the wrong file. Could you send me the GameConfig.txt located in the bin folder of the source mod you are compiling for?

**Comment by CaskoChan** [comment]
[GameConfig.txt](https://github.com/ruarai/CompilePal/files/3187937/GameConfig.txt)

**Comment by Exactol** [comment]
I see the problem, your GameConfig starts with "GameConfig.txt", while Compile Pal expects it to start with "Configs". I'm not sure if this is an invalid GameConfig format, or if it's just that Compile Pal can't handle it. @CaskoChan

**Comment by CaskoChan** [comment]
Huh interesting, Im using https://forum.facepunch.com/dev/bvenk/Slammin-Source-map-tools/1/, im not sure if it changed the gameconfig, could you maybe updated compile pal to be more flexible with gameconfig?

**Comment by Exactol** [comment]
I can't find any other people who use the Slammin tools who's game config contained "GameConfig.txt", so I'm not sure why yours was like that. For the future, Compile Pal will no longer crash if it reads a bad game config and will log it. If this comes up more, I'll add support for reading game configs that start with "GameConfig.txt"

**Comment by MAGNAT2645** [comment]
I've same error when trying to launch v26:
```
System.NullReferenceException: object Reference not set to an instance of an object.
   in CompilePalX.GameConfigurationParser.Parse(String filename)
   in CompilePalX.LaunchWindow..ctor()
```
