### ISSUE TITLE
[Request] Searching for content to pack

### ISSUE THREAD

**Issue by Caskoo** [ruarai/CompilePal#74]
As of right now, compile pal only looks inside of the game directory, you're compiling for. It would be nice if there was the option to tell compile pal, to scan a folder you want outside of the game. When i used VIDE, i would tell it to scan a folder that i that contained extracted models from example l4d2 or csgo. What im asking is, add the option that'il let us tell compile to scan a folder specifed by the user, to then pack content from said folder. Thanks

**Comment by Exactol** [comment]
Still looking into it. Manual gameconfig creation is something planned for v27

From,
Zach Matuson

**Comment by Exactol** [comment]
I just realized that this might actually be a bug. I added support for hard coded paths in the GameConfig in 2427c8b. This should be part of the v26 release, if it's not working please let me know.

**Comment by Exactol** [comment]
Added the ability to specify additional search directories in #208
