### ISSUE TITLE
Clicking "Add Map" crashes for TF2

### ISSUE THREAD

**Issue by GHLeeroy** [ruarai/CompilePal#78]
Similar to issue #68, but CompilePal crashes upon clicking the Add Map button for Team Fortress 2
I've installed the latest version ,v26 and v26.1 but non of them work.
Crashlog from v26.1 : 
[2019-05-27T13-08-12.txt](https://github.com/ruarai/CompilePal/files/3221948/2019-05-27T13-08-12.txt)

**Comment by Exactol** [comment]
[CompilePal 026.1.zip](https://github.com/ruarai/CompilePal/files/3222035/CompilePal.026.1.zip)
Try this build, it might help

**Comment by GHLeeroy** [comment]
> [CompilePal 026.1.zip](https://github.com/ruarai/CompilePal/files/3222035/CompilePal.026.1.zip)
> Try this build, it might help

Oh, thank you very much. It works!
