### ISSUE TITLE
Program unable to launch

### ISSUE THREAD

**Issue by leeroytm** [ruarai/CompilePal#79]
Two days ago, Ive opened up an issue #78 , now I'm having a problem launching CompilePal in my laptop. It wont launch

Crashlog : 
[2019-05-30T12-29-36.txt](https://github.com/ruarai/CompilePal/files/3235431/2019-05-30T12-29-36.txt)

**Comment by GHLeeroy** [comment]
Still crashes
[2019-06-01T11-42-05.txt](https://github.com/ruarai/CompilePal/files/3243351/2019-06-01T11-42-05.txt)

**Comment by Exactol** [comment]
What version of .NET do you have installed?

**Comment by GHLeeroy** [comment]
I think I don't have it installed

**Comment by Exactol** [comment]
It should come with windows, you can check what version it is by opening regedit and going to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full

**Comment by GHLeeroy** [comment]
Here ya go
![Capture 1](https://user-images.githubusercontent.com/51069447/58773545-05f37f80-85f0-11e9-80a5-04211730b18f.PNG)

**Comment by Exactol** [comment]
I have no idea what could be causing this. My best guess is something in .NET got corrupted. Try running this tool to verify your .NET install. https://blogs.msdn.microsoft.com/astebner/2008/10/13/net-framework-setup-verification-tool-users-guide/

**Comment by Aspect12** [comment]
I'm having the same problem.

**Comment by JesseB1f** [comment]
I used the tool and it told me that my .NET is installed just fine, but the program still won't open. I have also tried running as administrator and in compatibility mode.

**Comment by Exactol** [comment]
Closing stale issues
