### ISSUE TITLE
[REQUEST] Add compile log error checker

### ISSUE THREAD

**Issue by Matt2468rv** [ruarai/CompilePal#8]
Hi there!  I've been using CompilePal for quite awhile now and I have a feature request/idea.  One of the most useful tools for mappers to check their work is the error page at Interlopers: http://www.interlopers.net/errors/

My request would be to add an error checker to CompilePal that scans for compile errors automatically after the compile has completed.  Maybe the interlopers error checker could even somehow be integrated into CompilePal?

I can just envision the CompilePal GUI having a little red notification bubble in the bottom corner if there are compile errors, or a green checkmark if no errors are present.  If errors are present, you could click on the notification and CompilePal would tell you what's wrong and what needs to be fixed.

CompilePal is a great application, and I think having this feature would honestly top it off and make it extremely popular for people to use as their primary map compiler.

**Comment by ruarai** [comment]
This is partially already a feature, and it was definitely inspired by the Interlopers error checker. Problem at the moment is it only checks for the fatal issues, like leaks.

There's no implementation for finding the little warnings that Interloper's can at the moment.

**Comment by Matt2468rv** [comment]
Gotcha.  If CompilePal had something on-par with the interlopers error checker, or if it even sent the log to the error checker and retrieved the results I think that would be excellent and extremely useful.  I'm not sure how difficult that would be to implement of course.

**Comment by ruarai** [comment]
I've implemented a basic version of this for you to test. It uses Interlopers' online source of errors that seems to be designed just for this.

I need to do some more testing to make sure it works correctly, and maybe get permission from Interlopers. You can try it out though: 

https://dl.dropboxusercontent.com/u/6898485/Compile%20Pal%20017.rar

**Comment by Matt2468rv** [comment]
Here's what happened when I tested it out:

![cperror](https://cloud.githubusercontent.com/assets/7517366/7376995/2f74e35a-eda9-11e4-91b8-bd78f035f2d1.jpg)

The FindPortalSide error is a standard error (at least for my map) that happens on every compile and isn't a big issue.  What I'm thinking is that it would be best not to have any errors at all cancel the compile, but rather run the entire compile process as usual and upon completion scan the log for errors and generate notifications.

I'm glad to see some preliminary progress though!  I'm sure Interlopers would be okay with it if you asked nicely. :)

**Comment by ruarai** [comment]
Added with new release!

**Comment by Matt2468rv** [comment]
Woohoo!  I'll give it a go as soon as I get the chance.

**Comment by Matt2468rv** [comment]
I tried it out and I really like what you've done, nice work!  Thanks for being so responsive to end-user feedback!  It's refreshing.  CompilePal is by far one of the most useful mapping tools out there! :+1:
