### ISSUE TITLE
Cubemaps are not generated by HL2DM

### ISSUE THREAD

**Issue by mbit-kiel** [ruarai/CompilePal#82]
**Summary**
Compile Pal 26X starts HL2:DM twice to compile both LDR and HDR cubemaps, however the game client always closes right after loading the map, without actually building cubemaps.

**Additional context**
The output of Compile Pal says 0 errors/warnings, see below for log extract.

I was curious how Compile Pal tries to instruct the game to build cubemaps, spied on the cmdline arguments to hl2.exe during another fruitless run, and copied those to the game's Launch Options in Steam. 
Voilá: starting the game through steam, the game correctly builds cubemaps and then closes, just as probably intended.  Then, I also looked at the cmdline arguments that Steam uses to start the game. What I found there was an extra ´-steam´. Perhaps Compile Pal is missing that, causing the game to behave strangely.

**Debug.log**
>Starting a 'cubemaps' compile.
>Starting compilation of dm_geh
>
>CompilePal - Cubemap Generator
>Detecting HDR levels...
>Map requires two sets of cubemaps
>Compiling LDR cubemaps...
>Compiling HDR cubemaps...
>Cubemaps compiled

>'cubemaps' compile finished in 00:00:17
>0 errors/warnings logged:
>  No errors/warnings logged for dm_geh

>'cubemaps' compile finished in 00:00:17
>0 errors/warnings logged:
>  No errors/warnings logged for dm_geh

**Comment by Exactol** [comment]
[Compile Pal 026.3.zip](https://github.com/ruarai/CompilePal/files/3539357/Compile.Pal.026.3.zip)
Sorry for the extremely late response, I've been extremely busy. Try out this build.

**Comment by Exactol** [comment]
Closing stale issues
