### ISSUE TITLE
Compatibility with Custom Versions of VRAD

### ISSUE THREAD

**Issue by Wii2** [ruarai/CompilePal#83]
**Is your feature request related to a problem? Please describe.**
I use a custom version of VRAD called BUMRad, which has some custom flags when compiling. This _shouldn't_ be an issue as CompilePal allows you to add more parameters to VRAD, however, you can only pick from preselected parameters. Meaning you have to use the 'CUSTOM' step instead, **but** this means CompilePal doesn't pick up on any errors or warnings BUMRad throws.

**Describe the solution you'd like**
Ideally, I'd just like to be able to add custom parameters to the preexisting steps. Something as basic as a 'custom parameter' option at the bottom of the list which would allow you to type in your own parameter. And also maybe a way to add it to the parameter list for future use.

**Describe alternatives you've considered**
Alternately, maybe an option in the CUSTOM step to warn the user when either predefined or user-defined words occur in the output. Akin to how CompilePal normally warns the user about warnings/errors for regular VRAD.

**Additional context**
No additional context.

**Comment by Exactol** [comment]
You can add your own parameters to the preselected parameters by editing the parameters.json file located in the Paramaters/VRAD folder. 
To add a new parameter, put something like this at the end of the parameter JSON array:
```
{
    "Name": "NAME OF PARAMETER",
    "Parameter": " PARAMETER PASSED",
    "Description": "DESCRIPTION OF PARAMETER",
    "Value": null,
    "CanHaveValue": false,
    "Warning": "WARNING IF APPLICABLE"
 }
```
I've been meaning to write a tutorial on this, but haven't had the time.

**Comment by Exactol** [comment]
You can now also pass custom parameters through the GUI. https://github.com/ruarai/CompilePal/releases/tag/v027.5
