### ISSUE TITLE
Packing Failed

### ISSUE THREAD

**Issue by Statua** [ruarai/CompilePal#84]
- This error is preventing the map from packing the content. 
- I haven't optimized the content yet. Is there a limit to how many files the packer can load and pack? 
- I saw on a previous thread this could be caused by a broken model but what model would be causing that? 
- There's 2 reporting outside the map but those errors were present and packed without issue before. Those models are also not outside the map but that a different discussion. 
- The map loads fine in Garry's Mod. 
- I compiled using slammin tools which again, have packed fine before.

`CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\bin
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\download
Reading BSP...
Initializing pak file...
Something broke:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at CompilePalX.Compilers.BSPPack.AssetUtils.findMdlMaterialsAndModels(String path, List`1 skins)
   at CompilePalX.Compilers.BSPPack.PakFile.AddModel(String internalPath, List`1 skins)
   at CompilePalX.Compilers.BSPPack.PakFile..ctor(BSP bsp, List`1 sourceDirectories, List`1 includeFiles, List`1 excludedFiles, List`1 excludedDirs)
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context)`

This is the map's compile log.

`materialPath: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\materials
Loading C:\Users\Jordan\Dropbox\maps\rp_monoford_v0a.vmf
Map revision 1191
ConVarRef mat_reduceparticles doesn't point to an existing ConVar
Can't find surfaceprop alttile for material OFFICE/TILE/TILE_FLOOR_001B, using default
Can't find surfaceprop alttile for material OFFICE/TILE/TILE_FLOOR_002, using default
Can't find surfaceprop marble for material AGENCY/WALL/MARBLE01, using default
Can't find surfaceprop marble for material AGENCY/FLOOR/MARBLE01A, using default
Can't find surfaceprop marble for material AGENCY/FLOOR/MARBLE02, using default
Can't find surfaceprop 1 for material STATUA/URBAN/BUILDING_01A, using default
Can't find surfaceprop upholstery for material PLASTER/CEILING_INSULATION03, using default
Can't find surfaceprop asphalt for material CONCRETE/ROADPARKINGLOT, using default
Can't find surfaceprop sheetrock for material WALLPAPER/YELLOW04, using default
Can't find surfaceprop sheetrock for material WALLPAPER/BLUE05, using default
Can't find surfaceprop sheetrock for material PLASTER/PLASTER_CEILING_01, using default
Can't find surfaceprop sheetrock for material WALLPAPER/YELLOW02, using default
Can't find surfaceprop sheetrock for material WALLPAPER/BLUE01, using default
Patching WVT material: maps/rp_monoford_v0a/statua/nature/blendforest_fur01_wvt_patch
Patching WVT material: maps/rp_monoford_v0a/blend/blend_rock_015_moss_002_wvt_patch
Patching WVT material: maps/rp_monoford_v0a/nature/blendrockmud01a_wvt_patch
Patching WVT material: maps/rp_monoford_v0a/statua/urban/blend_alley_dirt_wvt_patch
Patching WVT material: maps/rp_monoford_v0a/nature/blendsandrock004a_wvt_patch
Patching WVT material: maps/rp_monoford_v0a/statua/nature/blenddirtroad01_wvt_patch
Patching WVT material: maps/rp_monoford_v0a/asphalt/hr_c/hr_asphalt_001_wvt_patch
fixing up env_cubemap materials on brush sides...
0...1...2...3...4...5...6...7...8...9...10
FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (-4096.0 9864.0 -12680.0)
Leaf 0 contents: CONTENTS_WATER CONTENTS_AREAPORTAL CONTENTS_TRANSLUCENT 
Leaf 1 contents: CONTENTS_AREAPORTAL 
viscontents (node 0 contents ^ node 1 contents): CONTENTS_WATER 
This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_WATER 
Check for a huge brush enclosing the coordinates above that has contents CONTENTS_WATER 
Candidate brush IDs: Brush 2913127: 

0...1...2...3...4...5...6...7...8...9...10Processing areas...done (0)
Building Faces...done (1)
Chop Details...done (0)
Find Visible Detail Sides...
Merged 1178 detail faces...done (0)
Merging details...done (0)
FixTjuncs...
PruneNodes...
WriteBSP...
done (3)
writing C:\Users\Jordan\Dropbox\maps\rp_monoford_v0a.prt...Building visibility clusters...
done (1)
Finding displacement neighbors...
Found a displacement edge abutting multiple other edges.
Warning: invalid neighbor connection on displacement near (-14289.47 1169.41 -6464.92)
Warning: invalid neighbor connection on displacement near (-13437.00 272.95 -7168.00)
Warning: invalid neighbor connection on displacement near (-13952.00 768.00 -6465.00)
Finding lightmap sample positions...
Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
Building Physics collision data...
done (2) (1703684 bytes)
Static prop models/props_electric/fluorescent_light_006_brightness.mdl outside the map (7080.00, 5600.00, -11629.00)
Static prop models/props_street/harborviewhotel.mdl outside the map (4096.00, 2696.00, -11936.00)
Placing detail props : 0Material NATURE/GRASSLAWN_DRY01 uses unknown detail object type rural_dkdirt_grass! (suppressed further reports of this bug)
...1...2...3...4...5...6...7...8...9...10
Compacting texture/material tables...
Reduced 10155 texinfos to 5479
Reduced 1048 texdatas to 928 (52772 bytes to 47598)
Writing C:\Users\Jordan\Dropbox\maps\rp_monoford_v0a.bsp
Wrote ZIP buffer, estimated size 342685, actual size 252691
35 seconds elapsed

4 threads
reading c:\users\jordan\dropbox\maps\rp_monoford_v0a.bsp
reading c:\users\jordan\dropbox\maps\rp_monoford_v0a.prt
8982 portalclusters
22201 numportals
0...1...2...3...4...5...6...7...8...9...10
Optimized: 1280433 visible clusters (0.00%)
Total clusters visible: 21195283
Average clusters visible: 2359
Building PAS...
Average clusters audible: 4583
visdatasize:16272784  compressed from 20263392
writing c:\users\jordan\dropbox\maps\rp_monoford_v0a.bsp
20 seconds elapsed

[Reading texlights from 'lights.rad']
[45 texlights parsed from 'lights.rad']

Loading c:\users\jordan\dropbox\maps\rp_monoford_v0a.bsp
PREP OK
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
Patch Sample Radius Clamped!
25775 faces
16 degenerate faces
86226264 square feet [12416581632.00 square inches]
2784 Displacements
15786398 Square Feet [2273241344.00 Square Inches]
25759 patches before subdivision
1219893 patches after subdivision
1358 direct lights
0...1...2...3...4...5...6...7...8...9...10
0...1...2...3...4...5...6...7...8...9...10
transfers 45376876, max 1880
transfer lists: 346.2 megs
0...1...2...3...4...5...6...7...8...9...10	Bounce #1 added RGB(8300037, 7136251, 5503574)
0...1...2...3...4...5...6...7...8...9...10	Bounce #2 added RGB(269348, 218006, 179225)
0...1...2...3...4...5...6...7...8...9...10	Bounce #3 added RGB(479716, 361858, 174736)
0...1...2...3...4...5...6...7...8...9...10	Bounce #4 added RGB(14104, 10931, 8070)
0...1...2...3...4...5...6...7...8...9...10	Bounce #5 added RGB(33604, 22969, 8409)
0...1...2...3...4...5...6...7...8...9...10	Bounce #6 added RGB(2140, 1865, 1517)
0...1...2...3...4...5...6...7...8...9...10	Bounce #7 added RGB(3022, 2150, 1061)
0...1...2...3...4...5...6...7...8...9...10	Bounce #8 added RGB(621, 619, 533)
0...1...2...3...4...5...6...7...8...9...10	Bounce #9 added RGB(511, 464, 350)
0...1...2...3...4...5...6...7...8...9...10	Bounce #10 added RGB(243, 262, 226)
0...1...2...3...4...5...6...7...8...9...10	Bounce #11 added RGB(168, 180, 151)
0...1...2...3...4...5...6...7...8...9...10	Bounce #12 added RGB(106, 119, 101)
0...1...2...3...4...5...6...7...8...9...10	Bounce #13 added RGB(72, 82, 69)
0...1...2...3...4...5...6...7...8...9...10	Bounce #14 added RGB(48, 56, 46)
0...1...2...3...4...5...6...7...8...9...10	Bounce #15 added RGB(33, 38, 32)
0...1...2...3...4...5...6...7...8...9...10	Bounce #16 added RGB(22, 26, 21)
0...1...2...3...4...5...6...7...8...9...10	Bounce #17 added RGB(15, 18, 15)
0...1...2...3...4...5...6...7...8...9...10	Bounce #18 added RGB(10, 12, 10)
0...1...2...3...4...5...6...7...8...9...10	Bounce #19 added RGB(7, 9, 7)
0...1...2...3...4...5...6...7...8...9...10	Bounce #20 added RGB(5, 6, 5)
0...1...2...3...4...5...6...7...8...9...10	Bounce #21 added RGB(3, 4, 3)
0...1...2...3...4...5...6...7...8...9...10	Bounce #22 added RGB(2, 3, 2)
0...1...2...3...4...5...6...7...8...9...10	Bounce #23 added RGB(2, 2, 1)
0...1...2...3...4...5...6...7...8...9...10	Bounce #24 added RGB(1, 1, 1)
0...1...2...3...4...5...6...7...8...9...10	Bounce #25 added RGB(1, 1, 1)
Build Patch/Sample Hash Table(s).....Done<1.0991 sec>
0...1...2...3...4...5...6...7...8...9...10
FinalLightFace Done
Computing detail prop lighting : 0...1...2...3...4...5...6...7...8...9...10
0 of 0 (0% of) surface lights went in leaf ambient cubes.
0...1...2...3...4...5...6...7...8...9...10
Writing leaf ambient...done
Computing static prop lighting : 00...1...2...3...4...5...6...7...8...9...10
Ready to Finish

Object names       Objects/Maxobjs  Memory / Maxmem  Fullness 
------------       ---------------  ---------------  -------- 
models                 272/4096        13056/196608   ( 6.6%) 
brushes               4677/32768       56124/393216   (14.3%) 
brushsides           32435/65536      259480/524288   (49.5%) 
planes               17406/65536      348120/1310720  (26.6%) 
vertexes             48634/65536      583608/786432   (74.2%) 
nodes                21550/65536      689600/2097152  (32.9%) 
texinfos              5479/12288      394488/884736   (44.6%) 
texdata                928/2048        29696/65536    (45.3%) 
dispinfos             2784/0          489984/0        ( 0.0%) 
disp_verts           81360/0         1627200/0        ( 0.0%) 
disp_tris           109248/0          218496/0        ( 0.0%) 
disp_lmsamples     6480752/0         6480752/0        ( 0.0%) 
faces                25775/65536     1443400/3670016  (39.3%) 
hdr faces            25775/65536     1443400/3670016  (39.3%) 
origfaces            13268/65536      743008/3670016  (20.2%) 
leaves               21823/65536      698336/2097152  (33.3%) 
leaffaces            31197/65536       62394/131072   (47.6%) 
leafbrushes          20908/65536       41816/131072   (31.9%) 
areas                   61/1024          488/8192     ( 6.0%) 
surfedges           156505/512000     626020/2048000  (30.6%) 
edges               109520/256000     438080/1024000  (42.8%) 
LDR worldlights          0/16384           0/1441792  ( 0.0%) 
HDR worldlights       1358/16384      119504/1441792  ( 8.3%) 
leafwaterdata            8/32768          96/393216   ( 0.0%) 
waterstrips              0/131072          0/1310720  ( 0.0%) 
waterverts               0/131072          0/1572864  ( 0.0%) 
waterindices             0/131072          0/262144   ( 0.0%) 
cubemapsamples         234/1024         3744/16384    (22.9%) 
overlays               776/1024       273152/360448   (75.8%) 
LDR lightdata         [variable]           0/0        ( 0.0%) 
HDR lightdata         [variable]    54463700/0        ( 0.0%) 
visdata               [variable]    16272784/16777216 (97.0%) VERY FULL!
entdata               [variable]     1214220/393216   (308.8%) VERY FULL!
LDR ambient table    21823/65536       87292/262144   (33.3%) 
HDR ambient table    21823/65536       87292/262144   (33.3%) 
LDR leaf ambient     21823/65536      611044/1835008  (33.3%) 
HDR leaf ambient    150157/65536     4204396/1835008  (229.1%) VERY FULL!
occluders                0/0               0/0        ( 0.0%) 
occluder polygons        0/0               0/0        ( 0.0%) 
occluder vert ind        0/0               0/0        ( 0.0%) 
detail props          [variable]           1/4935456  ( 0.0%) 
dtl prp lght          [variable]           1/4        (25.0%) 
HDR dtl prp lght      [variable]           1/4        (25.0%) 
static props          [variable]           1/737706   ( 0.0%) 
pakfile               [variable]     1475171/0        ( 0.0%) 
physics               [variable]     1703684/4194304  (40.6%) 
physics terrain       [variable]      538224/1048576  (51.3%) 

Level flags = 2

Total triangle count: 51638
Writing c:\users\jordan\dropbox\maps\rp_monoford_v0a.bsp
52 minutes, 24 seconds elapsed
`

**Comment by Exactol** [comment]
Can you try the latest experimental version and tell me if it still crashes.

**Comment by Statua** [comment]
Awesome. It worked and spewed out the faulty models for me. I find it odd that I can still pack them manually tho.

**Comment by Exactol** [comment]
Could you upload the models that are failing so I can try to find out why?

**Comment by Statua** [comment]
Yes I can do that later this week hopefully.

**Comment by Statua** [comment]
[brokemodels.zip](https://github.com/ruarai/CompilePal/files/3531211/brokemodels.zip)

These are all the ones that showed up.

**Comment by Exactol** [comment]
[Compile Pal 026.3.zip](https://github.com/ruarai/CompilePal/files/3539336/Compile.Pal.026.3.zip)
Try this out

**Comment by Statua** [comment]
Getting this: 

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\gmodhammer\garrysmod\addons\
Found search path: C:\gmodhammer\garrysmod
Found search path: C:\gmodhammer\garrysmod
Found search path: C:\gmodhammer\garrysmod\bin
Found search path: C:\gmodhammer\garrysmod\download
Reading BSP...
Something broke:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at CompilePalX.Compilers.BSPPack.BSP.buildModelList() in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\BSP.cs:line 271
   at CompilePalX.Compilers.BSPPack.BSP..ctor(FileInfo file) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\BSP.cs:line 77
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 141

**Comment by Exactol** [comment]
Could you upload your unpacked bsp?

**Comment by Statua** [comment]
I wont be able to do that with this particular map due to it being a commission. Sorry. 

I tried it on another map. It worked, however when it made the unpacked file, it didnt make a packed .bsp and instead, the unpacked file was packed.

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\gmodhammer\garrysmod\addons\
Found search path: C:\gmodhammer\garrysmod
Found search path: C:\gmodhammer\garrysmod
Found search path: C:\gmodhammer\garrysmod\bin
Found search path: C:\gmodhammer\garrysmod\download
Reading BSP...
Initializing pak file...
Writing file list...
Running bspzip...
Copying packed bsp to vmf folder...
FAILED - Could not find C:\gmodhammer\garrysmod\maps\gm_planex_playground.bsp

**Comment by Exactol** [comment]
Can you consistently reproduce this and if so what are the steps to create the bug?

**Comment by Statua** [comment]
I get the bug every time i try to compile it. I select the map vmf i want to load within my map directory. Then i got compile with pack being the only selected process. No extra parameters.

**Comment by Exactol** [comment]
[Compile Pal 026.4.zip](https://github.com/ruarai/CompilePal/files/3694881/Compile.Pal.026.4.zip)
Can you try this and send me the debug.log in the Compile Pal folder

**Comment by Statua** [comment]
Ran the pack. It didnt have any issues making backup copies this time. It changed the filesize of the map to 1.3gb (it should be closer to 1.5 after packing). When I loaded the map, it crashed with "Map has no textures". Here's the debug log:

`Fetching update information...
Loaded JSON metadata PACK from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\PACK\meta.json at order 11
Loaded JSON metadata CUBEMAPS from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\CUBEMAPS\meta.json at order 9
Loaded JSON metadata NAV from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\NAV\meta.json at order 8
Loaded JSON metadata SHUTDOWN from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\SHUTDOWN\meta.json at order 20
Loaded JSON metadata UTILITY from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\UTILITY\meta.json at order 10
Loaded JSON metadata CUSTOM from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\CUSTOM\meta.json at order 15
Loaded JSON metadata COPY from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\COPY\meta.json at order 4
Loaded JSON metadata GAME from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\GAME\meta.json at order 13
Loaded JSON metadata REPACK from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\REPACK\meta.json at order 12
Loaded JSON metadata STATS from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\STATS\meta.json at order 14
Loaded JSON metadata VBSP from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\VBSP\meta.json at order 1
Loaded JSON metadata VRAD from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\VRAD\meta.json at order 3
Loaded JSON metadata VVIS from C:\Users\Jordan\Desktop\Hammer\Compile Pal 025\Debug\Compile Pal 026.4\Parameters\VVIS\meta.json at order 2
Added preset Fast for processes VBSP, VVIS, VRAD, COPY, NAV, CUBEMAPS, UTILITY, PACK, REPACK, GAME, STATS, CUSTOM, SHUTDOWN
Added preset Full - Both for processes VBSP, VVIS, VRAD, COPY, NAV, CUBEMAPS, UTILITY, PACK, REPACK, GAME, STATS, CUSTOM, SHUTDOWN
Added preset Full - HDR for processes VBSP, VVIS, VRAD, COPY, NAV, CUBEMAPS, UTILITY, PACK, REPACK, GAME, STATS, CUSTOM, SHUTDOWN
Added preset Full - LDR for processes VBSP, VVIS, VRAD, COPY, NAV, CUBEMAPS, UTILITY, PACK, REPACK, GAME, STATS, CUSTOM, SHUTDOWN
Added preset Normal for processes VBSP, VVIS, VRAD, COPY, NAV, CUBEMAPS, UTILITY, PACK, REPACK, GAME, STATS, CUSTOM, SHUTDOWN
Added preset Publish - Both for processes VBSP, VVIS, VRAD, COPY, NAV, CUBEMAPS, UTILITY, PACK, REPACK, GAME, STATS, CUSTOM, SHUTDOWN
Added preset Publish - HDR for processes VBSP, VVIS, VRAD, COPY, NAV, CUBEMAPS, UTILITY, PACK, REPACK, GAME, STATS, CUSTOM, SHUTDOWN
Updater found that Compile Pal is up to date.
Starting a 'Publish - Both' compile.
Starting compilation of rp_monoford_v0a

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\gmodhammer\garrysmod\addons\
Found search path: C:\gmodhammer\garrysmod
Found search path: C:\gmodhammer\garrysmod
Found search path: C:\gmodhammer\garrysmod\bin
Found search path: C:\gmodhammer\garrysmod\download
Reading BSP...
Initializing pak file...
An exception was caught by the ExceptionHandler:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at CompilePalX.Compilers.BSPPack.AssetUtils.findMdlMaterialsAndModels(String path, List`1 skins) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\AssetUtils.cs:line 103
   at CompilePalX.Compilers.BSPPack.PakFile.AddModel(String internalPath, List`1 skins) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\PakFile.cs:line 233
Failed to read file C:\gmodhammer\garrysmod/models/gmod_tower/theater_seat.mdl
Writing file list...
Running bspzip...
Copying packed bsp to vmf folder...
Copying C:\gmodhammer\garrysmod\maps\rp_monoford_v0a.bsp to C:\gmodhammer\garrysmod\maps\rp_monoford_v0a.bsp.unpacked
Copying E:\SteamLibrary\steamapps\common\GarrysMod\garrysmod\maps\rp_monoford_v0a.bsp to C:\gmodhammer\garrysmod\maps\rp_monoford_v0a.bsp
Finished!
---------------------
1683 materials found
935 models found
0 particle files found
63 sounds found
additional files: 
-detail file
---------------------

'Publish - Both' compile finished in 00:01:24
0 errors/warnings logged:
  No errors/warnings logged for rp_monoford_v0a
`

**Comment by Exactol** [comment]
Could you upload C:\gmodhammer\garrysmod/models/gmod_tower/theater_seat.mdl?

**Comment by Exactol** [comment]
[Compile Pal 026.4.zip](https://github.com/ruarai/CompilePal/files/3722054/Compile.Pal.026.4.zip)
This version fixes some issues with packing multiple bodyparts. It might fix your issue.

**Comment by Statua** [comment]
[theatreseat.zip](https://github.com/ruarai/CompilePal/files/3747223/theatreseat.zip)
It had the same result as last time. Game crashes with 'Map with no textures.'

```
Starting a 'Fast' compile.
Starting compilation of rp_monoford_v0a

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\bin
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\download
Reading BSP...
Initializing pak file...
An exception was caught by the ExceptionHandler:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at CompilePalX.Compilers.BSPPack.AssetUtils.findMdlMaterialsAndModels(String path, List`1 skins) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\AssetUtils.cs:line 103
   at CompilePalX.Compilers.BSPPack.PakFile.AddModel(String internalPath, List`1 skins) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\PakFile.cs:line 233
Failed to read file C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod/models/gmod_tower/theater_seat.mdl
Writing file list...
Running bspzip...
Copying packed bsp to vmf folder...
Finished!
---------------------
2173 materials found
952 models found
0 particle files found
154 sounds found
additional files: 
-soundscape
-detail file
---------------------

'Fast' compile finished in 00:02:58
0 errors/warnings logged:
  No errors/warnings logged for rp_monoford_v0a
```

[debug.log](https://github.com/ruarai/CompilePal/files/3747224/debug.log)

**Comment by Statua** [comment]
![Capture](https://user-images.githubusercontent.com/54192360/67151929-48fa7a80-f293-11e9-94db-dac5a99d786a.JPG)
I opened it in GCFScape to see what was going on in the bsp. Everything is blank. There aren't even any lumps in there that can be seen. But it's showing at 1.7gb filesize which is what it should be at with the packed content at this point. That tells me it is loading the files but it's corrupting the bsp somehow.

**Comment by Exactol** [comment]
[CompilePAl 026.5.zip](https://github.com/ruarai/CompilePal/files/3748063/CompilePAl.026.5.zip)
This should fix the theatre chair failing to pack. Are you sure you aren't hitting some engine limit with how much content you are packing?

**Comment by Exactol** [comment]
Closing stale issues
