### ISSUE TITLE
Crash on launch (0.26.2 & 0.26.3)

### ISSUE THREAD

**Issue by killer89** [ruarai/CompilePal#86]
CompilePal crashes on launch.

Reinstalling didn't solve the issue. Tried both 0.26.2 and 0.26.3

**debug.txt**

An exception was caught by the ExceptionHandler:
System.NullReferenceException: You cannot specify an object instance as a reference for an object.
  in target CompilePalX.GameConfigurationParser.Parse(String filename) file C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\GameConfigurationParser.cs:line 151
  in target CompilePalX.LaunchWindow..ctor() tiedostossa C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\LaunchWindow.xaml.cs:line 62

**Comment by Exactol** [comment]
Can you send the crash log? It should be in the CrashLog folder.

**Comment by killer89** [comment]
> 
> Can you send the crash log? It should be in the CrashLog folder.
> […](#)
> On Sep 9, 2019, at 12:40 AM, killer89 ***@***.***> wrote: CompilePal crashes on launch. Reinstalling didn't solve the issue. Tried both 0.26.2 and 0.26.3 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

It was same as in debug.txt:

System.NullReferenceException: object Reference not set to an instance of an object.
   in CompilePalX.GameConfigurationParser.Parse(String filename) file C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\GameConfigurationParser.cs:line 151
   in CompilePalX.LaunchWindow..ctor() file C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\LaunchWindow.xaml.cs:line 62

Would love to know though, whose directory that is pointing to, though, since there is no such (10zil) profile on my pc.

**Comment by Exactol** [comment]
10zil is my directory, that's just for debug symbols. Can you also send me the gameconfig.txt for the game you are compiling for? It should be in your game directory's bin folder.

**Comment by killer89** [comment]
> 
> 10zil is my directory, that's just for debug symbols. Can you also send me the gameconfig.txt for the game you are compiling for? It should be in your game directory's bin folder.
> […](#)
> On Sep 9, 2019, at 10:48 AM, killer89 ***@***.***> wrote: Can you send the crash log? It should be in the CrashLog folder. … On Sep 9, 2019, at 12:40 AM, killer89 @.***> wrote: CompilePal crashes on launch. Reinstalling didn't solve the issue. Tried both 0.26.2 and 0.26.3 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. It was same as in debug.txt: System.NullReferenceException: object Reference not set to an instance of an object. in CompilePalX.GameConfigurationParser.Parse(String filename) file C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\GameConfigurationParser.cs:line 151 in CompilePalX.LaunchWindow..ctor() file C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\LaunchWindow.xaml.cs:line 62 Would love to know though, whose directory that is pointing to, though, since there is no such (10zil) profile on my pc. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.


It was blank.

The configurations were added to it, when i launched hammer again. There was a system crash yesterday (likely due to new gpu, which still has some wrinkles), and CompilePal started to act up after it. For some reason the gameconfig.txt was seemingly wiped, and it was restored when i ran hammer again.

**Comment by Exactol** [comment]
Did it work after being regenerated?

**Comment by killer89** [comment]
> 
> Did it work after being regenerated?
> […](#)
> On Sep 9, 2019, at 11:23 AM, killer89 ***@***.***> wrote: 10zil is my directory, that's just for debug symbols. Can you also send me the gameconfig.txt for the game you are compiling for? It should be in your game directory's bin folder. … On Sep 9, 2019, at 10:48 AM, killer89 @.> wrote: Can you send the crash log? It should be in the CrashLog folder. … On Sep 9, 2019, at 12:40 AM, killer89 @.> wrote: CompilePal crashes on launch. Reinstalling didn't solve the issue. Tried both 0.26.2 and 0.26.3 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. It was same as in debug.txt: System.NullReferenceException: object Reference not set to an instance of an object. in CompilePalX.GameConfigurationParser.Parse(String filename) file C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\GameConfigurationParser.cs:line 151 in CompilePalX.LaunchWindow..ctor() file C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\GameConfiguration\LaunchWindow.xaml.cs:line 62 Would love to know though, whose directory that is pointing to, though, since there is no such (10zil) profile on my pc. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. It was blank. The configurations were added to it, when i launched hammer again. There was a system crash yesterday (likely due to new gpu, which still has some wrinkles), and CompilePal started to act up after it. For some reason the gameconfig.txt was seemingly wiped, and it was restored when i ran hammer again. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Yeah.

More specifically the system crash occured when the compiling was in process, and the gameinfo.txt was wiped out because of this.
Would it be possible to add some sort of notice on failed start, if the issue is caused by blank / corrupted gameconfig.txt?

**Comment by Exactol** [comment]
Yea, better error feedback is something I plan on adding eventually.
