### ISSUE TITLE
Pack option not picking up particle system

### ISSUE THREAD

**Issue by Grublet** [ruarai/CompilePal#87]
[minecraft_particles_ttt.zip](https://github.com/ruarai/CompilePal/files/3711384/minecraft_particles_ttt.zip)
[debug.log](https://github.com/ruarai/CompilePal/files/3711401/debug.log)

Compile Pal 26.2x

**Bug Description**
Ran CompilePal with pack option, when completed it shows "0 particle files found."
Particle .pcf file is located in "C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\Particles" 

Do the particles need to be in the map a specific way to be identified by CompilePal?
In the map they're created as info_particle_system objects with their name matching the name string from the particle system.

**Steps to reproduce**
Steps to reproduce the behavior.
Attached the particle system I'm using, create info_particle_system with **Particle System Name** "torch"

**Expected behavior**
Want the .pcf file to be packed and the particle manifest to be created as /maps/MAPNAME_particles.txt

**Comment by WildBanan** [comment]
particles pack correctly for cs go!

**Comment by Grublet** [comment]
> 
> 
> particles pack correctly for cs go!

Yeah I'm jealous, I want it to work for Gmod too!
I can use the -include parameter to explicitly pack the .pcf file, but I really want it to create the particle manifest file as well in /maps. If there was an option to set this I'd be happy happy.

**Comment by maxdup** [comment]
Out of curiosity, can you try renaming your particles folder to a lowercase "p"? Source isn't case-sensitive in places where compilepal might be.

**Comment by Grublet** [comment]
> Out of curiosity, can you try renaming your particles folder to a lowercase "p"? Source isn't case-sensitive in places where compilepal might be.

No luck, renamed Particles folder to particles and it shows 0 particle files found.
When I use the -include parameter to pack the .pcf file it shows 1 particle files found, but it does not generate the particle manifest in /maps unfortunately.

**Comment by Exactol** [comment]
[Compile Pal 026.4.zip](https://github.com/ruarai/CompilePal/files/3720865/Compile.Pal.026.4.zip)
Can you try this?

**Comment by Grublet** [comment]
> [Compile Pal 026.4.zip](https://github.com/ruarai/CompilePal/files/3720865/Compile.Pal.026.4.zip)
> Can you try this?

No luck, after compile it shows 0 particle files found.
With include option, no particle manifest created.

[debug.log](https://github.com/ruarai/CompilePal/files/3720915/debug.log)
[debug_explicit_include.log](https://github.com/ruarai/CompilePal/files/3720916/debug_explicit_include.log)

**Comment by Exactol** [comment]
I think the issue is that you have no particle manifest. Compile Pal will not pack your particles unless one exists. You can generate a particle manifest with Compile Pal by adding the `Utility` step and adding the `Generate Particle Manifest` option

**Comment by Exactol** [comment]
Author of the issue reached out through GitHub and told me this was resolved
