### ISSUE TITLE
Map has no textures - engine error

### ISSUE THREAD

**Issue by killer89** [ruarai/CompilePal#88]
Started to get this engine error yesterday. For some reason the custom content is not packed into the map file after compiling and custom content packing is done, but the map file however seemingly breaks up, and in-game crashes with "map has no textures" - engine error message.

I was using 0.26.4 when the issue started to appear, and downgraded all the way to 0.26.2, with no luck. The game in question was Half-Life 2: Episode Two.

The map compiles and runs normally, if the custom content is not packed into the map file with CompilePal. (Map compiling itself works in CompilePal.)

I tested custom content packaging with pakrat, and it didn't have issues with packing, and the map launched normally in-game.

[debug.log](https://github.com/ruarai/CompilePal/files/3751028/debug.log)

**Comment by Exactol** [comment]
Can you upload the textures/assets that you are trying to pack?

**Comment by killer89** [comment]
I did some research, and discovered the reason for the crashing:

Before the crashing started to occur, i had been packing the custom content into the map, and the file size had been around 124mb, which is fine. However yesterday i added a motorcycle model to the map (material files alone are 193mb), and some time later the custom content packaging stopped working and the crash occurred.  When i excluded the motorcycle's files from the packaging, the custom content was once again packed normally into the map file, and it didn't crash in-game.

Apparently there is some sort of limit of how big the bsp can be.

**Comment by Exactol** [comment]
Did compile pal throw any errors when it tried to pack the motorcycle?

**Comment by Exactol** [comment]
[CompilePal 026.5.zip](https://github.com/ruarai/CompilePal/files/3753023/CompilePal.026.5.zip)
Try this and send the debug.log and any crash logs if they appear

**Comment by killer89** [comment]
CompilePal crashed again on 0.26.5, when it was about to pack the custom content, excluding the motorcycle.


[debug.log](https://github.com/ruarai/CompilePal/files/3755290/debug.log)

**Comment by Exactol** [comment]
Can you upload the motorcycle model?

**Comment by killer89** [comment]
https://drive.google.com/file/d/1fKXeAf59TGnu5yamA1F6KiQ5NclIszid/view?usp=sharing

In-game it works without issues, however it messes up the custom content packing, and breaks the compiled bsp. Also CompilePal seems to ignore the  -excludedir command, which i used on both the motorcycle's material and model directories.

**Comment by Exactol** [comment]
[CompilePal 026.6.zip](https://github.com/ruarai/CompilePal/files/3776035/CompilePal.026.6.zip)
Try this out

**Comment by killer89** [comment]
It seems to be working now.

Cheers. :)

**Comment by killer89** [comment]
The changes / fixes in 0.26.6 weren't carried over to 0.27?

**Comment by Exactol** [comment]
Are you sure you installed correctly? I just tried it and it worked fine. Can you upload your crash/debug logs?

**Comment by killer89** [comment]
I extracted the files to a new folder, copied over only the game settings, and compiled / packed content on two maps several times, and it seems to work now.

Apparently "upgrade installation" didn't work out.

**Comment by killer89** [comment]
The issue has started to pop up again. I have tried 0.27.5 and 0.27.6 versions with fresh install.

[debug.log](https://github.com/ruarai/CompilePal/files/4144764/debug.log)

**Comment by Exactol** [comment]
Is the issue with excluding directories or in-game crashes?

**Comment by killer89** [comment]
Latter.

**Comment by Exactol** [comment]
Hmm, I just tested it in TF2 and it seems to be working fine. Can you send me the bsp after packing?

**Comment by killer89** [comment]
Did you try to pack the motorcycle model into it?

**Comment by Exactol** [comment]
Closing stale issues, please try the latest prerelease and if the issue is still happening feel free to reopen
