### ISSUE TITLE
Turn off PC after map compile end

### ISSUE THREAD

**Issue by kilroy98** [ruarai/CompilePal#91]
**Is your feature request related to a problem? Please describe.**
When map is to big, its compiled so long.

**Describe the solution you'd like**
Add function to set computer turn off after map compile end.

**Describe alternatives you've considered**
-

**Additional context**
-
p.s. sorry for my english, i use google translate.

**Comment by Exactol** [comment]
This is already a feature. Add the Shutdown step and it will shutdown your computer after the map compiles.
