### ISSUE TITLE
Support for Slartibarty's updated vbsp / vrad commands

### ISSUE THREAD

**Issue by killer89** [ruarai/CompilePal#92]
https://knockout.chat/thread/992/1

**Comment by Exactol** [comment]
I don't plan on supporting custom compilers, but there are community made configs. Here is the Slartibarty one: https://drive.google.com/file/d/1RKbnrKgNrEjScoxFHKVnM_c2VKCMj694/view . To install it, drag the Parameters folder into your Compile Pal folder and replace the files when it prompts you.
