### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by Oplkill** [ruarai/CompilePal#95]
What about to make linux version?

**Comment by maxdup** [comment]
Linux or Mac is not really feasible right now. The codebase is mostly C# which could be ported to run on Linux and Mac but the UI code is based on WPF, which will likely only ever run on windows. If a multi-platform version CompilePal was to be made, it would probably be a new project entirely with a different graphic framework.

but who knows, keep an eye open. With source 2 on the horizon being more and more multiplatform, we may see some new compile tools pop up.
