### ISSUE TITLE
Packing Failed

### ISSUE THREAD

**Issue by Mattmad1234** [ruarai/CompilePal#96]
Hello all!
Im having a packing error causing my map not to make the proper bsp file. I am new to map making so I could just be missing something, but so far I have yet to find a fix.

During the final stages of compiling and packing I receive this error using V027. 

Reading BSP...
Initializing pak file...
Writing file list...
Running bspzip...
Copying packed bsp to vmf folder...
FAILED - Could not find F:\SteamLibrary\steamapps\common\GarrysMod\garrysmod\maps\rp_mercury_sw.bsp

This Error happens every time I try and pack any map using CompilePal. The resulting file that this creates is
rp_mercury_sw.bsp.unpacked

Here is an uploaded debug log for all the information.

[debug.log](https://github.com/ruarai/CompilePal/files/4051397/debug.log)

**Comment by Exactol** [comment]
Can you try the latest prerelease and see if this error still happens?

**Comment by worMatty** [comment]
Could be caused by having the VMF in the game’s maps dir. It’s trying to copy the map onto itself.

**Comment by Exactol** [comment]
This should be fixed in https://github.com/ruarai/CompilePal/releases/tag/v027.10
