### ISSUE TITLE
Packing failed

### ISSUE THREAD

**Issue by karsonatorz** [ruarai/CompilePal#99]
**Describe the bug**
Something broke.
```
 CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\bin
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\download
Reading BSP...
Something broke:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CompilePalX.Compilers.BSPPack.BSPPack.UnpackBSP(String unpackDir) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 339
   at CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context) in C:\Users\10zil\OneDrive\Documents\Projects\C Sharp\CompilePal\CompilePalX\Compilers\BSPPack\Pack.cs:line 179 
```
Seems to happen with all my BSPs. Happens when run as admin.

**Steps to reproduce**
Create map, add textures, compile, fail

**Expected behavior**
Packing to successfully work

**Debug.txt**
[debug.log](https://github.com/ruarai/CompilePal/files/4132830/debug.log)

**Additional context**
Compilepal v27 and v27.05 compiling for Garry's Mod

**Comment by Exactol** [comment]
Can you upload the gameConfigs.json file located in the GameConfiguration folder of Compile Pal

**Comment by karsonatorz** [comment]
`[
  {
    "GameFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\garrysmod",
    "VBSP": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\bin\\vbsp.exe",
    "VVIS": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\bin\\vvis.exe",
    "VRAD": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\bin\\vrad.exe",
    "BSPZip": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\bin\\bspzip.exe",
    "VBSPInfo": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\bin\\vbspinfo.exe",
    "VPK": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\bin\\vpk.exe",
    "GameEXE": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\hl2.exe",
    "MapFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\garrysmod\\maps",
    "SDKMapFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\content\\garrysmod\\mapsrc",
    "BinFolder": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\GarrysMod\\bin",
    "Name": "Garry's Mod"
  }
]`

**Comment by Exactol** [comment]
Can you confirm that bspzip.exe exists at location `C:/Program Files (x86)/Steam/steamapps/common/GarrysMod/bin/bspzip.exe`? And if not, try verifying your game files through steam.

**Comment by karsonatorz** [comment]
https://i.imgur.com/8YytoHq.png 
There it be.

**Comment by karsonatorz** [comment]
Hmm... I tried deleting it and then validating game files, and now it doesn't give an error, but it gets stuck. 
`CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found wildcard path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons\
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\bin
Found search path: C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\download
Reading BSP...
Initializing pak file...
Writing file list...
Running bspzip...

`
